export default {
    JOURNEY_REFRESH: 'JOURNEY_REFRESH',
    JOURNEY_REQUEST_FAIL: 'JOURNEY_REQUEST_FAIL',
    JOURNEY_REQUEST_SUCCESS: 'JOURNEY_REQUEST_SUCCESS',
    JOURNEY_CHANGRE_TEXT: 'JOURNEY_CHANGRE_TEXT',
    JOURNEY_LOADMORE: 'JOURNEY_LOADMORE',
    JOURNEY_NOMORE: 'JOURNEY_NOMORE',
    JOURNEY_CLEAN:'JOURNEY_CLEAN',
    JOURNEY_CHANGRE_TYPE: 'JOURNEY_CHANGRE_TYPE',
    CONSUME_REFRESH: 'CONSUME_REFRESH',
    CONSUME_REQUEST_FAIL: 'CONSUME_REQUEST_FAIL',
    CONSUME_REQUEST_SUCCESS: 'CONSUME_REQUEST_SUCCESS',
    CONSUME_CHANGRE_TEXT: 'CONSUME_CHANGRE_TEXT',
    CONSUME_LOADMORE: 'CONSUME_LOADMORE',
    CONSUME_NOMORE: 'CONSUME_NOMORE',
    CONSUME_CLEAN:'CONSUME_CLEAN',
    CONSUME_CHANGRE_TYPE: 'CONSUME_CHANGRE_TYPE',


    LANGUAGE_LOAD: 'LANGUAGE_LOAD',
    LANGUAGE_CHANGE: 'LANGUAGE_CHANGE',
    FEETYPETRANSFORM: 'FEETYPETRANSFORM',
    PASSENGER_REFRESH: 'PASSENGER_REFRESH',
    PASSENGER_REQUEST_FAIL: 'PASSENGER_REQUEST_FAIL',
    PASSENGER_REQUEST_SUCCESS: 'PASSENGER_REQUEST_SUCCESS',
    PASSENGER_LOADMORE:'PASSENGER_LOADMORE',
    PASSENGER_NOMORE:'PASSENGER_NOMORE',
    PASSENGER_RESET:'PASSENGER_RESET',
    APPLY_SET_VALUE:' APPLY_SET_VALUE',

    //企业订单刷新
    ENTERPRISEORDER_REFRESH:'ENTERPRISEORDER_REFRESH',
    ENTERPRISEORDER_REFRESH_FAIL:'ENTERPRISEORDER_REFRESH',
    ENTERPRISEORDER_REFRESH_SUCCESS:'ENTERPRISEORDER_REFRESH',

    // THEME_CHANGE: 'THEME_CHANGE',
    // THEME_INIT: 'THEME_INIT',

    //综合订单选人信息
    COMPCHECKTREVALLER_REFRESH:'COMPCHECKTREVALLER_REFRESH',
    COMPCHECKTREVALLER_REFRESH_FAIL:'COMPCHECKTREVALLER_REFRESH_FAIL',
    COMPCHECKTREVALLER_REFRESH_SUCCESS:'COMPCHECKTREVALLER_REFRESH_SUCCESS',
    
    //是否开启综合订单
    COMPREHENSIVESWITCH:'COMPREHENSIVESWITCH',
    //综合订单已选订单的出差人Travellers
    COMPSELECTTRAVELLERS:'COMPSELECTTRAVELLERS',
    COMPSELECTTRAVELLERS_SUCCESS:'COMPSELECTTRAVELLERS_SUCCESS',
    //综合订单点击继续预订存储当前综合订单Id
    COMPMASSORDERID:'COMPMASSORDERID',
    COMPMASSORDERID_SUCCESS:'COMPMASSORDERID_SUCCESS',
    //判断综合订单是创建的还是继续预订
    COMPCREATEBOOL:'COMPCREATEBOOL',
    COMPCREATEBOOL_SUCCESS:'COMPCREATEBOOL_SUCCESS',
    //新建综合订单页检查出差人数据储存
    COMPCHECKTREVALLERS:'COMPCHECKTREVALLERS',
    //基础信息userInfo custormerInfo
    CUSTORMERINFO_USERINFO:'CUSTORMERINFO_USERINFO',
    //综合订单选定差旅规则人
    REFERENCEEMPLOYEE:'REFERENCEEMPLOYEE',
    //酒店实时取消规则
    HOTELCANSELRULE:'HOTELCANSELRULE',

    // 高危城市
    HIGHRISKTYPE:"HIGHRISKTYPE",
    //返程高危城市标识
    HIGHRISKTYPE2:"HIGHRISKTYPE2",
    //酒店合住人
    HOTELSHAREARR:"HOTELSHAREARR",

    //国际机票机场英文名称
    AIRPORTENNAME:'AIRPORTENNAME',
    //各个业务相应的国籍证件类型
    PROFILECOMMONENUM:'PROFILECOMMONENUM',

}