export default {
    "福成机场": "FuchengAirport",
    "首都机场T1航站楼": "CapitalIntlAirportTerminal-1",
    "首都机场T2航站楼": "CapitalIntlAirportTerminal-2",
    "首都机场T3航站楼": "CapitalIntlAirportTerminal-3",
    "大兴国际机场":"Daxing Intl Airport",
    "南苑机场": "NanyuanAirport",
    "龙嘉机场": "LongjiaIntlAirport",
    "黄花机场T1航站楼": "HuanghuaIntlAirportTerminal-1",
    "黄花机场T2航站楼": "HuanghuaIntlAirportTerminal-2",
    "黄花机场T3航站楼": "HuanghuaIntlAirportTerminal-3",
    "奔牛机场": "BenniuAirport",
    "双流国际机场T1航站楼": "ShuangliuIntlAirportTerminal-1",
    "双流国际机场T2航站楼": "ShuangliuIntlAirportTerminal-2",
    "江北国际机场T1航站楼": "JiangbeiIntlAirportTerminal-1",
    "江北国际机场T2A航站楼": "JiangbeiIntlAirportTerminal-2A",
    "江北国际机场T2B航站楼": "JiangbeiIntlAirportTerminal-2B",
    "江北国际机场T3A航站楼": "JiangbeiIntlAirportTerminal-3A",
    "大理机场": "DaliAirport",
    "周水子机场": "ZhoushuiziIntlAirport",
    "大同机场": "YungangAirport",
    "佛山机场": "ShadiAirport",
    "长乐机场": "ChangleIntlAirport",
    "白云机场": "BaiyunIntlAirport",
    "两江机场": "LiangjiangIntlAirport",
    "龙洞堡机场T1航站楼": "LongdongbaoIntlAirportTerminal-1",
    "龙洞堡机场T2航站楼": "LongdongbaoIntlAirportTerminal-2",
    "太平机场": "TaipingIntlAirport",
    "美兰机场": "MeilanIntlAirport",
    "萧山机场A航站楼": "XiaoshanIntlAirportTerminal-A",
    "萧山机场B航站楼": "XiaoshanIntlAirportTerminal-B",
    "新桥机场": "XinqiaoIntlAirport",
    "屯溪机场": "TunxiIntlAirport",
    "白塔机场": "BaitaIntlAirport",
    "东山机场": "DongshanAirport",
    "遥墙机场": "YaoqiangIntlAirport",
    "九江机场": "LushanAirport",
    "长水机场": "ChangshuiIntlAirport",
    "中川机场": "ZhongchuanAirport",
    "贡嘎机场": "GonggarAirport",
    "三义机场": "SanyiAirport",
    "北郊机场": "BeijiaoAirport",
    "昌北机场T1航站楼": "ChangbeiIntlAirportTerminal-1",
    "昌北机场T2航站楼": "ChangbeiIntlAirportTerminal-2",
    "禄口机场": "LukouIntlAirport",
    "吴圩机场": "WuxuIntlAirport",
    "兴东机场": "XingdongAirport",
    "栎社机场": "LisheIntlAirport",
    "流亭机场T1航站楼": "LiutingIntlAirportTerminal-1",
    "流亭机场T2航站楼": "LiutingIntlAirportTerminal-2",
    "山海关机场": "BeidaiheAirport",
    "晋江机场": "JinjiangAirport",
    "凤凰机场": "FenhuangAirport",
    "虹桥机场T1航站楼": "HongqiaoIntlAirportTerminal-1",
    "虹桥机场T2航站楼": "HongqiaoIntlAirportTerminal-2",
    "浦东机场T1航站楼": "PudongIntlAirportTerminal-1",
    "浦东机场T2航站楼": "PudongIntlAirportTerminal-2",
    "桃仙机场T1航站楼": "TaoxianIntlAirportTerminal-1",
    "桃仙机场T2航站楼": "TaoxianIntlAirportTerminal-2",
    "桃仙机场T3航站楼": "TaoxianIntlAirportTerminal-3",
    "宝安机场T3航站楼": "Bao'an Intl Airport Terminal-3",
    "宝安国际机场": "Bao'an Intl Airport",
    "正定机场": "Zhengding Intl Airport ",
    "武宿机场T1航站楼": "Wusu Intl Airport Terminal-1",
    "武宿机场T2航站楼": "Wusu Intl Airport Terminal-2",
    "滨海机场": "Binhai Intl Airport ",
    "威海机场": "Dashuibo Airport ",
    "龙湾国际机场": "Yongqiang Intl Airport ",
    "天河机场T1航站楼": "Tianhe Intl Airport Terminal-1",
    "天河机场T2航站楼": "Tianhe Intl Airport Terminal-2",
    "地窝堡机场T1航站楼": "Diwopu Intl Airport Terminal-1",
    "地窝堡机场T2航站楼": "Diwopu Intl Airport Terminal-2",
    "地窝堡机场T3航站楼": "Diwopu Intl Airport Terminal-3",
    "硕放机场": "Sunan Shuofang Airport ",
    "高崎机场": "Gaoqi Intl Airport ",
    "咸阳机场T1航站楼": "Xianyang Intl Airport Terminal-1",
    "咸阳机场T2航站楼": "Xianyang Intl Airport Terminal-2",
    "咸阳机场T3航站楼": "Xianyang Intl Airport Terminal-3",
    "曹家堡机场": "Caojiabao Airport ",
    "嘎洒机场": "Xishuangbanna Gasa Int Airport ",
    "观音机场": "Guanyin Airport ",
    "蓬莱国际机场": "Penglai Intl Airport ",
    "三峡机场": "Sanxia Airport ",
    "河东机场": "Hedong Airport ",
    "荷花机场": "Hehua Airport ",
    "新郑机场": "Xinzheng Intl Airport ",
    "金湾机场": "Jinwan Airport ",
    "九华山机场": "Jiuhuashan Airport ",
    "九黄机场": "Jiuzhai Huanglong Airport "
}