export default 
    {
        "中国": "China",
        "美国": "United States",
        "日本": "Japan",
        "英国": "United Kingdom",
        "中国香港": "Hong Kong",
        "中国澳门": "Macao",
        "中国台湾": "Taiwan",
        "伯利兹": "Belize",
        "佛得角": "Cape Verde",
        "亚美尼亚": "Armenia",
        "危地马拉": "Guatemala",
        "塔吉克斯坦": "Tajikistan",
        "圭亚那": "Guyana",
        "阿曼": "Oman",
        "安圭拉": "Anguilla",
        "牙买加": "Jamaica",
        "南非": "South Africa",
        "埃及": "Egypt",
        "老挝": "Laos",
        "洪都拉斯": "Honduras",
        "巴林": "Bahrain",
        "阿尔及利亚": "Algeria",
        "尼日利亚": "Nigeria",
        "吉尔吉斯斯坦": "Kyrgyzstan",
        "斯里兰卡": "Sri Lanka",
        "黎巴嫩": "Lebanon",
        "卢森堡": "Luxembourg",
        "安哥拉": "Angola",
        "哥斯达黎加": "Costa Rica",
        "巴拿马": "Panama",
        "巴基斯坦": "Pakistan",
        "爱沙尼亚": "Estonia",
        "摩尔多瓦": "Moldova",
        "阿塞拜疆": "Azerbaijan",
        "立陶宛": "Lithuania",
        "塞浦路斯": "Cyprus",
        "拉脱维亚": "Latvia",
        "哈萨克斯坦": "Kazakhstan",
        "卡塔尔": "Qatar",
        "玻利维亚": "Bolivia",
        "斯洛文尼亚": "Slovenia",
        "马其顿": "Macedonia",
        "斯洛伐克": "Slovakia",
        "马耳他": "Malta",
        "多米尼加": "Dominican",
        "文莱": "Brunei",
        "巴拉圭": "Paraguay",
        "冰岛": "Iceland",
        "科威特": "Kuwait",
        "委内瑞拉": "Venezuela",
        "白俄罗斯": "Belarus",
        "韩国": "South Korea",
        "印度": "India",
        "以色列": "Israel",
        "芬兰": "Finland",
        "土耳其": "Turkey",
        "厄瓜多尔": "Ecuador",
        "新加坡": "Singapore",
        "荷兰": "Netherlands",
        "乌拉圭": "Uruguay",
        "克罗地亚": "Croatia",
        "捷克": "Czech",
        "奥地利": "Austria",
        "印尼": "Indonesia",
        "保加利亚": "Bulgaria",
        "柬埔寨": "Cambodia",
        "秘鲁": "Peru",
        "阿尔巴尼亚": "Albania",
        "爱尔兰": "Ireland",
        "越南": "Viet Nam",
        "希腊": "Greece",
        "匈牙利": "Hungary",
        "智利": "Chile",
        "罗马尼亚": "Romania",
        "波兰": "Poland",
        "乌克兰": "Ukraine",
        "阿联酋": "United Arab Emirates",
        "葡萄牙": "Portugal",
        "马来西亚": "Malaysia",
        "比利时": "Belgium",
        "丹麦": "Denmark",
        "瑞典": "Sweden",
        "沙特阿拉伯": "Saudi Arabia",
        "挪威": "Norway",
        "阿根廷": "Argentina",
        "新西兰": "New Zealand",
        "哥伦比亚": "Colombia",
        "瑞士": "Switzerland",
        "菲律宾": "Philippines",
        "德国": "Germany",
        "法国": "France",
        "泰国": "Thailand",
        "俄罗斯": "Russia",
        "西班牙": "Spain",
        "澳大利亚": "Australia",
        "意大利": "Italy",
        "加拿大": "Canada",
        "墨西哥": "Mexico",
        "巴西": "Brazil",
        "波黑": "Bosnia & Herzegovina",
        "法属波利尼西亚": "French polynesia",
        "阿富汗": "Afghanistan",
        "黑山": "Montenegro",
        "尼泊尔": "Nepal",
        "孟加拉国": "Bangladesh",
        "瓜德罗普": "Guadeloupe",
        "马提尼克": "Martinique",
        "巴勒斯坦": "Palestinian territories",
        "关岛": "Guam",
        "安道尔": "Andorra",
        "安提瓜和巴布达": "Antigua & Barbuda",
        "美属萨摩亚": "American Samoa",
        "阿鲁巴": "Aruba",
        "奥兰群岛": "Aland",
        "巴巴多斯": "Barbados",
        "布基纳法索": "Burkina Faso",
        "布隆迪": "Burundi",
        "贝宁": "Benin",
        "圣巴泰勒米": "Saint-Barthelemy",
        "百慕大": "Bermuda",
        "荷兰加勒比区": "Caribbean Netherlands",
        "巴哈马": "Bahamas",
        "不丹": "Bhutan",
        "布韦岛": "Bouvet Island",
        "博茨瓦纳": "Botswana",
        "科科斯群岛": "Cocos Islands",
        "加纳": "Ghana",
        "圣文森特和格林纳丁斯": "St. Vincent & the Grenadines",
        "尼加拉瓜": "Nicaragua",
        "科特迪瓦": "Cote d'Ivoire",
        "中非": "Central African Republic",
        "喀麦隆": "Cameroon",
        "古巴": "Cuba",
        "圣诞岛": "Christmas Island",
        "吉布提": "Djibouti",
        "多米尼克": "Dominica",
        "西撒哈拉": "Western Sahara",
        "厄立特里亚": "Eritrea",
        "斐济": "Fiji",
        "福克兰群岛": "Falkland Islands",
        "密克罗尼西亚": "Micronesia",
        "法罗群岛": "Faroe Islands",
        "加蓬": "Gabon",
        "格林纳达": "Grenada",
        "格鲁吉亚": "Georgia",
        "法属圭亚那": "French Guiana",
        "直布罗陀": "Gibraltar",
        "格陵兰": "Greenland",
        "几内亚": "Guinea",
        "赤道几内亚": "Equatorial Guinea",
        "南乔治亚岛和南桑威奇群岛": "South Georgia and the South Sandwich Islands",
        "几内亚比绍": "Guinea-Bissau",
        "赫德岛和麦克唐纳群岛": "Heard Island and McDonald Islands",
        "海地": "Haiti",
        "马恩岛": "Isle of Man",
        "英属印度洋领地": "British Indian Ocean Territory",
        "伊拉克": "Iraq",
        "伊朗": "Iran",
        "泽西岛": "Jersey",
        "约旦": "Jordan",
        "基里巴斯": "Kiribati",
        "科摩罗": "Comoros",
        "开曼群岛": "Cayman Islands",
        "列支敦士登": "Liechtenstein",
        "利比里亚": "Liberia",
        "莱索托": "Lesotho",
        "利比亚": "Libya",
        "摩洛哥": "Morocco",
        "摩纳哥": "Monaco",
        "法属圣马丁": "Saint-Martin (France)",
        "马达加斯加": "Madagascar",
        "马绍尔群岛": "Marshall islands",
        "马里": "Mali",
        "缅甸": "Myanmar",
        "毛里塔尼亚": "Mauritania",
        "蒙塞拉特岛": "Montserrat",
        "马尔代夫": "Maldives",
        "马拉维": "Malawi",
        "纳米比亚": "Namibia",
        "尼日尔": "Niger",
        "诺福克岛": "Norfolk Island",
        "瑙鲁": "Nauru",
        "巴布亚新几内亚": "Papua New Guinea",
        "皮特凯恩群岛": "Pitcairn Islands",
        "波多黎各": "Puerto Rico",
        "帕劳": "Palau",
        "留尼汪": "Reunion",
        "塞尔维亚": "Serbia",
        "卢旺达": "Rwanda",
        "所罗门群岛": "Solomon Islands",
        "塞舌尔": "Seychelles",
        "苏丹": "Sudan",
        "斯瓦尔巴和扬马延": "Svalbard and Jan Mayen",
        "塞拉利昂": "Sierra Leone",
        "圣马力诺": "San Marino",
        "塞内加尔": "Senegal",
        "索马里": "Somalia",
        "苏里南": "Suriname",
        "南苏丹": "South Sudan",
        "圣多美和普林西比": "Sao Tome & Principe",
        "萨尔瓦多": "El Salvador",
        "叙利亚": "Syria",
        "斯威士兰": "Swaziland",
        "特克斯和凯科斯群岛": "Turks & Caicos Islands",
        "乍得": "Chad",
        "多哥": "Togo",
        "托克劳": "Tokelau",
        "东帝汶": "East Timor",
        "突尼斯": "Tunisia",
        "汤加": "Tonga",
        "图瓦卢": "Tuvalu",
        "坦桑尼亚": "Tanzania",
        "乌干达": "Uganda",
        "梵蒂冈": "Vatican City",
        "英属维尔京群岛": "British Virgin Islands",
        "美属维尔京群岛": "United States Virgin Islands",
        "瓦利斯和富图纳": "Wallis and Futuna",
        "萨摩亚": "Samoa",
        "也门": "Yemen",
        "马约特": "Mayotte",
        "赞比亚": "Zambia",
        "津巴布韦": "Zimbabwe",
        "刚果共和国": "Republic of the Congo",
        "刚果（金）": "Democratic Republic of the Congo",
        "莫桑比克": "Mozambique",
        "根西岛": "Guernsey",
        "冈比亚": "Gambia",
        "北马里亚纳群岛": "Northern Mariana Islands",
        "埃塞俄比亚": "Ethiopia",
        "新喀里多尼亚": "New Caledonia",
        "瓦努阿图": "Vanuatu",
        "法属南部领地": "French Southern Territories",
        "纽埃": "Niue",
        "美国本土外小岛屿": "United States Minor Outlying Islands",
        "库克群岛": "Cook Islands",
        "特立尼达和多巴哥": "Trinidad & Tobago",
        "朝鲜": "North Korea",
        "土库曼斯坦": "Turkmenistan",
        "乌兹别克斯坦": "Uzbekistan",
        "圣基茨和尼维斯": "St. Kitts & Nevis",
        "圣皮埃尔和密克隆": "Saint-Pierre and Miquelon",
        "圣赫勒拿": "St. Helena & Dependencies",
        "圣卢西亚": "Saint Lucia",
        "毛里求斯": "Mauritius",
        "肯尼亚": "Kenya",
        "蒙古国": "Mongolia",
        "库拉索": "Curacao",
        "荷属圣马丁": "Sint Maarten",
        "南极洲": "Antarctica",
        "安道尔共和国":"Andorra",
    

    
}