export default {
    // 1、	searchScreen.js
    '国内机票': 'Domestic Flights',
    '火车票': 'Trains',
    '差旅标准': 'Policy',
    '国内机票:不限': 'Domestic Flights: Unlimited',
    '出发城市或到达城市不能为空': 'Departure city or arrival city cannot be null',
    '出发城市和到达城市不能一样': 'Departure city and arrival city can not be the same',
    '单程': 'One way',
    '往返': 'Round trip',
    '出发城市': 'Departure city',
    '到达城市': 'Arrival city',
    '查询': 'Search',
    '清除历史': 'Clear',
    // 2、	FlightListScreen.js
    '起飞时间': 'Departure time',
    '不限': 'Any Class',
    '出发机场': 'Departure airport',
    '到达机场': 'Arrival airport',
    '航司': 'Airline',
    '舱位': 'Class',
    '头等舱': 'First Class',
    '公务舱': 'Business Class',
    '商务舱': 'Business Class',
    '经济舱': 'Economy Class',
    '实际承运': 'Operate by ',
    '获取数据失败请重试': 'Failed to obtain data. please try again',
    '终于回来了，航班可能有变化，将为您重新查询': 'There are something may be modified, will it again',
    '取消': 'Withdraw',
    '确定': 'Confirm',
    '获取更多价格失败': 'Failed to search more fare',
    '获取更多价格异常': 'Get more price exceptions',
    '所选时间不能小于当前时间': 'The selected date cannot be earlier than the current date',
    '获取春秋退改规则失败': 'Failed to obtain the fare rules from Spring Airlines',
    '包含航司规定必须产品': 'Including the products required',
    '春秋航空产品绑定失败': 'Spring airlines failed to bind products',
    '差旅规则检查': 'Travel policies monitoring',
    '差旅规则检测失败': 'Failed to monitor the travel policies',
    '很抱歉，查询无结果': 'sorry，there is no result',
    '经停': 'Transit via',
    '转': 'Transit via',
    '共享': 'Code share',
    '渠道价': 'Sale',
    '航司直销': 'airline direct sales',
    '预订': 'Book',
    '退改规则': 'Fare Rules',
    '舱位专享': 'Exclusive space',
    '前一天': 'Before',
    '后一天': 'Next',
    '从早到晚': 'Departure(Earliest)',
    '价格排序': 'Price',
    '筛选': 'Filters',
    '全价': 'Full fare',
    '有餐食': 'Meal(s)',
    '无餐食': 'No meal',
    '{{noun}}折': '{{noun}} off',
    '出差原因不能为空': 'Travel reasons should not be empty',
    '成本中心不能为空': 'The cost center cannot be empty',
    '备注不能为空': 'Note cannot be empty',
    '审批单号不能为空': 'The approval number cannot be empty',
    '大兴机场距离市区46公里，搭乘地铁到市区（草桥站）需约30分钟': 'Beijing Daxing Airport is 46km away from downtown. It may take 30 minutes by subway from Daxing airport to downtown (Caoqiao Station).',
    //  3、	FlightRuleScreen.js

    'RC标准': 'RC standard',
    '请选择未选择最低价的原因': 'Select the reason for not choosing the advance booking',
    '未提前预订的原因': 'Specify the reason',
    '请选择未选择提前预定的原因': 'Select the reason why you did not choose advance booking',
    '1、根据贵公司差旅政策规定，您未选择最低价舱位航班，故请您选择原因:': '1、Only lowest fare is allowed according to company travel policy. Please choose out-of-policy reasons.',
    '根据贵公司差旅政策规定，您未提前**天预订航班，故请您选择原因:': 'According to your companys travel policy, you have not booked the flight in advance, so please choose your reason',
    '请选择': 'Please select',
    '请选择(必填)': 'Please select(required)',
    '请选择(选填)': 'Please select(optional)',
    '继续预订': 'Continue',
    '您确定继续预订吗？': 'Are you sure you want to continue?',
    '陪同客户或领导': 'Accompany customer/Boss',
    '航空公司偏好': 'Airline preference',
    '机场选择': 'Airport Preference',
    '改签或退票因素': 'Unsuitable change or cancellation policy',
    '起飞和到达时间不合适': 'Unsuitable departure/arrival time',
    '经批准可不选择最低价': 'Already got other forms of approval',
    '出差期刚确认完': 'Business travel schedule just confirmed',
    '原定出差计划临时变更': 'Original schedule change',
    '计划外的紧急出差任务': 'Unplanned urgent business travel',
    '根据贵公司差旅政策规定，您未提前{{noun}}天预订航班，故请您选择原因:': 'Base on th travel policy of your company , you should book the flight at least {{noun}} days in advance . Please select the reason why',
    // 11、	FlightEditPassengerScreen.js

    '请完善数据': 'Please improve the data',
    '手机号格式不正确': 'Format of cell phone number is wrong',
    '证件号不能为空': 'The ID number cannot be empty',
    '出生日期不能为空': 'Date of birth cannot be empty',
    '性别不能为空': 'Gender cannot be empty',
    '请输入正确的邮箱格式': 'Please enter the correct mailbox format',
    '证件': 'Certificate',
    '姓名,与登机所持证件中的姓名一致': 'The name is consistent with the name of the certificate held in the registration',
    '手机号码': "Mobile number",
    '手机号码(必填)': "Cell phone number (required)",
    '证件号码(必填)': 'ID number (required)',
    '请先完善数据': 'Select perfect data',
    '请输入生日': 'Please input birthday',
    '邮箱(选填)': 'Email (optional)',
    '请输入生日(必填)': 'Please input birthday(required)',
    '未知(必填)': 'Unknown(required)',
    '请输入联系人电话': 'Please enter your contact number',
    //10、	FlightContidionScreen.js
    '默认': 'Default',
    '恢复默认': 'Default',
    '选择常用旅客': 'Select frequent travelers',

    // 4、	FlightOrderScreen.js
    '联系人': 'Name',
    '添加其他联系人姓名': 'Add another contact name',
    '电话': 'Phone',
    '电话号码': 'Telephone number',
    '电子邮件': 'Email',
    '部门出差': 'Department',
    '按员工所属部门': 'Department of employees',
    '项目出差': 'Project of business',
    '审批单号': 'Approval number',
    '请填写审批单号': 'Please enter the approval number',
    '请填写审批单号(必填)': 'Please enter the approval number(Required)',
    '请填写审批单号(选填)': 'Please enter the approval number（Optional）',
    '必填': 'Required',
    '（必填）': '（Required）',
    '（选填）': '（Optional）',
    '选填': 'Optional',
    '出差原因': 'Reason for business trip',
    '请填写出差原因': 'Please enter the reason for business trip',
    '请填写出差原因(必填)': 'Please enter the cause(Required)',
    '请填写出差原因(选填)': 'Please enter the cause(Optional)',
    '成本中心': 'Cost center',
    '请填写成本中心': 'Please enter the cost center',
    '请填写成本中心(必填)': 'Please enter the cost center(Required)',
    '请填写成本中心(选填)': 'Please enter the cost center(Optional)',
    '备注': 'Remarks',
    '请填写备注': 'Please enter remarks',
    '请填写备注(必填)': 'Please enter remarks(Required)',
    '请填写备注(选填)': 'Please enter remarks(Optional)',
    '您的订单尚未填写完成,是否确定要离开当前页面?': 'You have not finished the booking yet. Do you want to leave the current page?',
    '订单填写': 'Book Tickets',
    '只能为自己预订': 'Can only book for self',
    '最大入住人数为9人': 'Maximum occupancy of 9 persons',
    '编辑乘客': 'Edit Passenger Info',
    '用户不能为空': 'User cannot be empty',
    '最多购买人数为9人,请手动删除多余人员': 'the Maximum purchase is 9, Please delete redundant personnel.',
    '证件号码不能为空': 'The ID number cannot be empty',
    '{{noun}}证件号码不能为空': '{{noun}} The ID number cannot be empty',
    '男': 'Male',
    '女': 'Female',
    '与': 'and',
    '身份证': 'ID card',
    '未知': 'Unknown',
    '性别没有填写': 'Gender not specified',
    '{{noun}}性别没有填写': '{{noun}} Gender not specified',
    '出生日期没有填写': 'Date of birth not given',
    '{{noun}}出生日期没有填写': '{{noun}} Date of birth not given',
    '实施阶段': 'Implementation phase',
    '不能为空': 'It can not be empty',
    '{{noun}}不能为空': '{{noun}} Cant be empty',
    '{{noun}}格式不符合规则':'{{noun}} Format does not conform to rules',
    '请填写配送地址': 'Please fill in the delivery address',
    '获取审批信息失败': 'Failed to get approval information',
    '去': 'go',
    '返': 'back',
    '添加其他员工': 'Add other employees',
    '添加常用旅客': 'Add frequent passenger',
    '报销/购票凭证': 'Claims/purchase vouchers',
    '(含行程单保险发票)': '(Including itinerary, insurance invoices)',
    '配送方式': 'Shipping method',
    '寄出': 'sent out',
    '修改日期': 'date modified',
    '配送地址': 'shipping address',
    '请选择配送地址': 'Please select the shipping address',
    '添加发票抬头': 'Add invoice header',
    '新增发票抬头': 'New Invoice Header',
    '保存发票抬头': 'Save',
    'Vip服务费': 'VIP service fee',
    '服务费': 'Service fee',
    '明细': 'Detail',
    '民航基金+燃油': 'Tax & Fee',
    '邮递费用': 'postage fee',
    '机票价': 'Airfare',
    '份': 'policy',
    '人': 'people',
    '未选择最低价的原因': 'Specify the reason',
    '(含服务费)': '(Service charge)',
    '选择其他员工': 'Select other employees',
    '（含服务费）': '(Service charge)',
    '提交订单失败出错,请重试!': 'Failed to submit the order, please try again!',
    '订单支付成功,您可去我的订单中查看': 'The order was paid successfully. You can check it in my order',
    // 13、	HeaderDetailView.js
    '行李限额': 'Baggage Allowance',
    '税费': 'taxes',
    '查看退改签': 'Ticket Restrictions',
    '订单确认': 'Order Confirmation',
    '订单生成成功，您可去我的订单中查看': 'The order is successfully generated. You can check it in my order',
    '提交订单失败，请重试': 'Failed to submit order. Please try again',
    '免审': 'Exempt review',
    '乘机人': 'Passenger',
    '费用归属': 'Cost center',
    '审批级别': 'Approval level',
    '审批人': 'Approver',
    '级': 'Level',
    '无': 'Null',
    '收起详情': 'Details',
    '我已阅读并同意': 'I have read and agreed',
    '乘机人姓名、证件号码为关键信息,如因错误信息发生后续费用将由您自行承担': 'Passenger’s name and contact number are key information for booking. Passengers shall be fully responsible for related cost and risks due to wrong information.',
    '乘车人姓名、证件号码为关键信息,如因错误信息发生后续费用将由您自行承担': 'Passenger’s name and contact number are key information for booking. Passengers shall be fully responsible for related cost and risks due to wrong information.',
    '选择申请单': 'Select applications',
    '生成订单': 'Create Order',
    '正在加载': 'Loading',
    '设置': 'Settings',
    // 16、	OrderListScreen.js
    '全部订单': 'Orders',
    '待付款单': 'Pending payment',
    '获取订单失败': 'Failed to get order',
    '获取待付款单失败': 'Failed to get payment pending',
    '获取支付信息失败': 'Failed to get payment information',
    '确定取消该订单么？': 'Are you sure you want to cancel the order?',
    '我再想想': 'I want to think again',
    '确定取消': 'confirm cancellation',
    '审订单成功': 'urge orders successfully',
    '催审订单失败': 'Failure to urge orders',
    '催审订单异常': 'Urge orders anomaly',
    '乘客姓名／航班号': 'Name of passenger/flight number',
    // 16、OrderListItem.js
    '付款': 'Pay',
    '退票': "Refund",
    '改签': 'Change',
    '催审': 'Remind',
    // 15、	OrderDetailScreen.js
    '获取订单详情失败': 'Failed to get order details',
    '获取附加信息失败': 'Failed to get additional information',
    '订单详情': 'Order Details',
    '确定同意批准该订单么?': 'Are you sure you agree to approve the order?',
    '我再想想': 'Let me think',
    '确定同意': 'Yes, I approve',
    '批准成功': 'Approval of success',
    '请输入驳回的原因': 'Please enter reasons for rejection',
    '确定驳回': 'Reject',
    '驳回成功': 'Successful rejected',
    '驳回失败，请联系客服': 'Rejection failed, please contact customer service',
    '驳回异常，请联系客服': 'Rejection exception, please contact customer service',
    '违反最低价规则原因:': 'Out-of-policy Reasons:',
    '违反提前预定规则原因:': 'Out-of-policy Reasons:',
    '原因描述': 'Reason to describe',
    '订单状态': 'Order status',
    '改签原因': 'Reason for change',
    '退票原因': 'Reason for refund',
    '驳回原因': 'Reasons for rejection',
    '机型': 'Type',
    '共享航班': 'Shared flights',
    '订单总额': "Total orders",
    '当前金额不包含手续费，手续费按退改规则计算，以最终退票单为准。': 'The current amount does not include service charge. The handling fee shall be calculated according to the rule of refund and correction, whichever is the final refund note',
    '改签将产生票面差价及改期费，改期费用按退改规则计算，以最终改签单为准。': 'Change will result in face difference and rescheduling fee, and the replacement fee will be calculated according to the rule of refund and reform, whichever is the final change order',
    '票面差': 'Nominal value difference',
    '税差': 'Tax difference',
    '人数': 'Number of passenger',
    '改签费': 'Ticket changing fee',
    '票面': 'Par value',
    '保险': 'Insurance',
    '退票费': 'refund fee',
    '票号': 'Ticket number',
    '提交申请': 'Submit the application',
    '审批流程': 'Approval process',
    '不同意': 'Disagree',
    '同意': 'Agree',
    '展开详情': 'detail',

    //  17、	OrderRefundScreen.JS

    '退票申请': 'Ticket refund application',
    '机票退票将产生退票费，退票费用按退改规则计算，是否继续提交退票?': 'Ticket refund will result in refund fee. Refund fee will be calculated according to the refund rule. Do you want to continue to submit refund?',
    '请选择退票原因': 'Please select the reason for refund',
    '请填写退票原因': 'Please fill in the reason for refund',
    '提交退票失败': 'Failure to submit a refund',
    '提交退票异常': 'Submit refund anomaly',
    '旅客行程改变自愿申退': 'Refund of change plan',
    '航班变动申请全退': 'Application for full refund of flight change',
    '其他（需输入原因）': 'Other (need to enter reasons)',
    '请输入退票原因': 'Please enter the reason for the refund of the ticket',
    //   8、	FlightChangeSearch.js
    '舱位不限': 'No limit class',
    //   7、	FlightChangeDetail.js
    '改签申请': 'Application for change',
    '机票改签将产生票面差价及改签费，改签费用按退改规则计算，是否继续提交改签？': 'Change of ticket will result in ticket price difference and change fee. The fee for change of ticket will be calculated according to the rule of refund and reform. Do you want to continue to submit the change application?',
    '请选择改签原因': 'Please select the reason for the change',
    '请输入原因': 'Please input the reason',
    '改签订单提交成功': 'Change order submitted successfully.',
    '提交订单失败': 'Failed to submit order',
    '因公司原因行程改签': 'Change of itinerary due to company reasons',
    '因个人原因行程改签': 'Change of itinerary for personal reasons',
    '请输入改签原因': 'Please enter reasons for change',
    '重新选择': 'Re-select',
    '确认改签': 'Confirm change',
    '确定改签': 'Confirm change',
    // 14、	ModifyRulesView.js
    '请联系客服': 'Please contact customer service ',
    '请联系客服～': 'Please contact customer service ~',
    '大客户已减': 'Reduced',
    '机建': 'Airport fee',
    '退改签规则': 'Rules of ticket changing & Refund',
    '更改条件': 'Ticket changing conditions',
    '退票条件': 'Refund conditions',
    '航班起飞前，请联系客服。': 'Please contact customer service before the flight takes off',
    '航班起飞后，请联系客服。': 'Please contact customer service after the departure of the flight',
    // 9、	FlightCityScreen.js
    '城市选择': 'Choose Cities',
    '字母检索': 'Alphabet search',

    '城市名称': 'Name of city',
    '热门': 'Popular Cities',
    '搜索结果': 'Search results',


    //    个人中心  

    // 10、	PersonalScreen.js

    '我的': 'My',
    '退出': 'Exit',
    '在线值机': 'check-in',
    '退出登录失败': 'Logout failed',
    '申请单列表': 'Application list',
    '未使用订单': 'Unused order',
    '分享给好友': 'Share to your friends',
    '用车订单': 'Car Service',
    '国际酒店订单': 'International Hotels',
    '港澳台及国际机票订单': 'Hongkong,Macau,Taiwan and International Flights',
    '火车票订单': 'Trains',
    '国内酒店订单': 'Domestic Hotels',
    '机票订单': 'Domestic Flights',
    '修改密码': 'Change Password',
    '个人信息': 'Personal information',
    '公告': 'Announcement',
    '获取用户信息异常': 'Obtaining user information anomaly',
    '常用乘机人': 'Passenger',
    '问题反馈': 'Problem feedback',


    '小型': 'S',
    '中型': 'M',
    '大型': 'L',
    //    7、	NoticeListScreen.js

    '公告列表': 'Bulletin List',
    '获取公告失败': 'failure',
    // 6、	ModifyPassword.js
    '请输入当前密码': 'Current password',
    '请输入新密码': 'Please enter a new password',
    '请再次输入新密码': 'Confirm new password',
    '修改密码成功，请重新登录': 'Revise the password successfully, please log in again',
    '修改密码失败': 'password failed',
    '修改密码异常': 'password abnormity',
    '当前密码': 'Password',
    '新密码': 'New password',
    '确认新密码': 'Confirm',
    '必须为6～20位字母或数字': 'Should be 6~20 letters or digits',
    '公告详情': 'Details of the announcement',
    // 9、	PersonalInfoScreen.js
    '护照': 'Passport',
    '台湾通行证': 'Taiwan pass',
    '港澳通行证': 'Hong Kong and Macao pass',
    '台胞证': 'Tainwan compatriot permit',
    '军人证': 'Military personnel ID',
    '回乡证': 'Home return permit',
    '请填写证件类型': 'Please fill in the type of certificate',
    '更改信息成功': 'Change information success',
    '更改用户信息失败': 'Changing user information failure',
    '请选择生日': 'Please choose birthday',
    '请选择有效期': 'PLEASE FILL OUT YOUR NAME ',
    '证件号': 'Certificate number',
    '请输入所对应的证件号码': 'Please enter the corresponding Certificate number',
    '有效期至': 'Valid until',
    '手机号': 'Mobile phone',
    '请输入电话号码': 'Please enter the phone number',
    '邮箱': 'Email',
    '性别': 'Gender',
    '出生日期': 'Date of birth',
    '国籍': 'Nationality',
    '请输入国家': 'Please enter the country',
    '姓名': 'Full name',
    '公司': 'company',
    '完成': 'Done',
    '英文姓': 'Last name',
    '名': 'First name',
    '请填写英文姓': 'Please enter Last NAME',
    '英文名': 'First name',
    '请填写英文名': 'Please enter First NAME',
    '选择相册': 'Choose from photo album',
    //   5、	FeedBackScreen.js
    '反馈问题': 'Feedback problem',
    '证件上传': 'Upload identification document',
    '上传不能超过3张': 'No more than three uploads',
    '拍照': 'Taking pictures',
    '正在上传图片': 'Uploading pictures',
    '上传图片成功': 'Upload pictures successfully',
    '图片上传失败': "Image upload failed",
    '请选择相册': 'PLEASE CHOOSE THE PHOTO ALBUM',
    '请填写反馈内容': 'Please fill in the feedback content',
    '请填写联系人': 'Please fill in the contact',
    '请填写联系方式': 'Please fill in the contact information',
    '问题已成功反馈，感谢您对我们的反馈和宝贵意见': 'The problem has been successfully feedback, feel your feedback to us and valuable comments',
    '上传凭证(不超过3张)': 'Upload supporting document (NO MORE THAN three)',
    '上传失败': 'Upload failed',
    '联系方式': 'Mobile phone',
    // 15、	SetUpScreen.js
    '没有安装微信，请您安装微信之后再试': 'Not having WeChat APP installed, please try again after installing',
    '商旅微信号': 'FCM SERVICE WECHAT',
    '当前版本号': 'Version Number',
    '清除缓存': "Clear Cache",
    '打开微信异常': 'Open the WeChat anomaly',
    // '    FCM是为企业用户提供出行全程服务，专注于旅行成本及大数据的管理，利用互联网+的技术和创新，提高客户商务旅行计划的整体效率及商务旅客的旅行体验': '  FCM TMC is one of the leading travel management companies in China focusing on total travel costs and big data management. With strong resources, data analysis capabilities and independent intellectual property business travel management system (including APP, PC, H5), call center , mail, WeChat and other service channels, it provides customers with trip approval before travel, complete travel product bookings (air tickets, train tickets, hotels, cars, insurance, visas, MICE), post-trip data analysis, overall travel management solutions. Save 10% -30% of overall travel expenses for enterprises    ',
    '多语言': 'Language',
    '简体中文': 'Simplified Chinese',
    // 7、	NoticeListScreen.js
    '获取公告失败': 'failure',
    // 13、	RequisitionList.js
    '获取申请单列表失败': 'Failed to obtain the application list',
    '亲，没有符合条件的订单啦~': 'There is no qualified order',
    '亲，没有符合条件的乘客啦~': 'There is no qualified Passenger',
    '已经加完全部': 'Load all',
    '正在加载更多数据': 'Loading more data...',
    '正在加载更多': 'Loading more ...',
    '正在加载更多...': 'Loading more ...',
    '未开通创建申请权限': 'No permission to create application',
    '获取用户配置信息失败': 'Failed to get user configuration information',
    '创建新申请单': 'Create a new application form',
    '正在刷新数据中...': 'Refreshing...',
    '正在刷新数据中': 'Refreshing...',
    '请输入联系人': "Please enter the contact person.",
    // 12、	RequisitionDetail.js
    '申请单详情': 'Details of the application',
    '获取申请单详情失败': 'Failure to get the details',
    '出差人': 'Business traveler',
    '所在部门': 'Department',
    '计划行程': 'Trip itinerary',
    '行程信息': 'Travel information',
    '业务类目': 'Application Category',
    '出差信息': 'Travel information',
    '提交人': 'submitter',
    '出差事由': 'reason of Business trip',
    '附加信息': 'Additional information',
    '附加': 'additional',
    // 3、	CategorySelect.js

    '业务类目': 'Booking class',
    '请选择类目': 'Please choose the category',
    // 16、	ShareItem.js
    '推荐下载FCM-企业商旅服务升级版，差旅预订，审批管理': 'Recommended downloads FCM - enterprise business travel service upgrade, travel booking, approval management',
    '微信': 'Wechat',
    '分享成功': 'Sharing success',
    '分享失败': 'Sharing failure',
    '朋友圈': 'Circle of friends',
    '空间': 'Space',

    // 17、	TravellerList.js
    '加载常旅客失败请重新加载': 'Please reload again',
    '请输入至少2个连续字进行搜索': 'Please enter at least 2 consecutive words for searching',
    '新增乘客': 'Add new passengers',
    '下拉刷新': 'Pull down to refresh',
    // 18、	UnUserOrderList.js 
    '用户信息异常': 'User information exception',

    '取消订单成功': 'Successfully canceled the order',
    '取消订单失败': 'Failed to cancel the orde',
    '催审订单成功': 'Urge to review the order successfully',
    '加载更多': 'Load more...',
    '没有更多订单了': 'There are no more orders',
    '乘客姓名/航班号': 'passenger name/ flight No.',
    '常用旅客': 'Frequent traveler',

    // 4、	EditTraveller.js
    '学生证': 'Student ID card',
    '编辑员工': 'Editor',
    '新增员工': 'Add employees',
    '获取乘客信息失败': 'Passenger information failure',
    '请填写姓名': 'Please fill out your name',
    '请填写国籍': 'Please fill in the nationality',
    '不支持该证件类型，请重新选择': 'IS NONSUPPORT THIS DOCUMENT, PLEASE RESELECTION',
    '请选择证件类型': 'Please choose the type of document',
    '请填写证件号码': 'Please fill in the identification number',
    '证件有效期不正确': 'The validity of the certificate is not correct',
    '证件有效期不足半年': 'The validity of documents is less than half a year',
    '请选择性别': 'Please select gender',
    '修改常旅客信息失败': 'Failed to modify frequent passenger information',
    '添加常旅客成功': 'Add success',
    '添加常旅客失败': 'Add failure',
    '请选择证件有效期': 'Please choose the expiration date of the certificate',
    '证件上的真实名称': 'The real name on the document',
    '姓氏': 'Surnames',
    '名称': 'NAME',
    '所属国家名称': 'Country',
    '证件类型': 'Document type',
    '证件号码': 'Identification document',
    '邮箱地址': 'Email address',
    // 1、	AddRequisition.js

    '获取客户配置信息失败': 'CUSTOMER INFORMATION FAILURE',
    '新建出差申请单': 'New application form',
    '日期': 'Date',
    '地点': 'Place',
    '请添加行程信息': 'Please add the travel information',
    '您的申请单已申请成功': 'Your application form has been applied successfully',
    '提交申请单失败': 'Failure to submit an application form',
    '出差事由': 'Reasons for travel',
    '请填写出差事由': 'Please fill out the Travel Cause',
    '出差类型': 'Travel type',
    '国内': 'domestic',
    '国际': 'international',
    '继续添加': 'Continue to add',
    '提交': 'Submit',
    '开始日期': 'Start date',
    '结束日期': 'End date',
    '出发城市不能为空': 'The departure city is not empty',
    '抵达城市不能为空': 'The arrival of the city is not empty',
    '出发日期不能为空': 'The departure date cannot be empty',
    '结束日期不能为空': "The end date cannot be empty",
    '业务类目不能为空': 'Booking class can not be empty',
    '上传附件': 'Uploading attachments',
    '没有安装QQ，请您安装QQ之后再试': 'No QQ is installed, please retry after installing QQ',
    '请描述你遇到的问题': "Please describe your problems",
    '出差单号': 'Business trip number',
    // 火车票  
    // 11、	SelectCityScreen.js
    '（改签）': '（Change）',
    '选择城市': 'Select city',
    '没有找到符合条件的城市': 'No qualified city was found',
    '请输入城市名称或简拼': 'City or abbreviation',
    '火车票:不限': 'Train ticket: Unlimited',
    '请选择出发城市': 'Please choose the city of departure',
    '请选择到达城市': 'Please choose to arrive in the city',
    '出发城市与到达城市不能相同': "The departure station and arrivall station can't be the same",
    '请选择出发日期': 'Please choose the departure date',
    '坐席': 'Seat',
    '请输入城市名称': 'Please enter the city name',
    '距离发车时间30分钟之内不允许提交改签': 'It is not allowed to submit a change within 30 minutes of departure time.',
    //    14、	TrainListScreen.js
    '出发': 'Departure',
    '到达': 'Arrive at',
    '耗时': 'Duration',
    '二等座': '2nd class',
    '一等座': '1st class',
    '商务座': 'Business class',
    '特等座': 'Premier seat',
    '高级软卧': 'Deluxe sleeper',
    '硬座': 'Hard seat',
    '无座': 'No seat',
    '软座': 'Soft seat',
    '硬卧': 'Hard sleeper',
    '软卧': 'Soft sleeper',
    '动卧': 'Sleeper',
    '已售完': 'Sold out',
    '无票': 'No ticket',
    '张': 'ticket(s)',
    '起': '↑',
    '获取火车票列表失败': 'Failed to get the train ticket list',
    '网络加载失败，请重试': 'loading network failed,please try again',
    '获取火车票列表异常': 'loading train ticket list abnormal',
    '不能再往前了': "Can't go forward",
    '普通列车': 'Regular train',
    '高铁动车': 'G Train - High Speed Train',
    '高铁': 'G Train',
    '动车': 'D Train',
    '一等座': "First Class Seat",
    '二等座': 'Second Class Seat',
    '商务座': "Business Class Seat",
    '软卧': 'Soft Sleeper',
    '高级软卧': 'Deluxe Soft Sleeper',
    '硬卧': 'Hard Sleeper',
    '软座': 'Soft Seat',
    '硬座': 'Hard Seat',
    '上铺': 'Upper Berth',
    '中铺': 'Middle Berth',
    '下铺': 'Lower Berth',
    '普通列车': 'Normal Train',
    '该车次车票已售完': 'The train ticket is sold out',
    '很抱歉，该日期两地无直达列车。请返回更改搜索条件重新搜索': 'Sorry, there are no direct trains between the two places on this date.Please return to change search criteria',
    '重新搜索': 'research again',
    '条件筛选': 'Filter',
    '车型': 'Type Of Train',
    '出发站': 'Departure station',
    '到达站': 'Arrivall station',
    '获取经停数据异常': 'Get stop data exception',

    // 12、	TicketDetailScreen.js
    '已售完，请选择其他票种': 'sold out, please select another seat',
    '{{noun}}已售完，请选择其他票种': '{{noun}} sold out, please select another seat',
    '超标': 'Out-of-policy',
    '时': 'h',
    '分': 'm',

    //  8、	RCReason.js
    '超标原因': 'Out-of-policy Reasons',
    '请选择未预订低价酒店的原因': 'Please select the reason for not booking a low-cost hotel',
    '请选择预订不可选席别的原因': 'Please select the reason',
    '未预订低价酒店的原因': 'Specify the reason',
    '未预订指定席别的原因': 'Specify the reason',

    // 1、	CreateOrderScreen.js
    '获取客户信息失败': 'Getting customer information failure',
    '获取当前用户信息失败': 'Getting current user information failure',
    '火车票全国通退通签并实施梯次退票 : 2014年12月3日起，票面乘车站开车前15天以上的，不收取退票手续费； 开车前48小时以上的，退票时收取票价5%的退票费； 开车前24小时以上、不足48小时的，退票时收取票价10%的退票费； 开车前不足24小时的，退票时收取票价20%。': "Ticket refund handing fees:1. 15+ days prior to departure :free2. 49 hours-15 days prior to departure :5% of ticket price 3. 25-49 hours prior to departure: 10% of ticket price4. Within 25 hours before departure: 20% of ticket price If a ticket has a departure date during the Spring Festial travel season and has already been changed,20% of the ticket price will be charged for refunds.we cannot change or cancel tickets that have already been picked up; please go to the railway station's refund window with your ticket and valid ID.",
    '火车票卧铺上\中\下是随机分配的，价格为下铺价。预订按实际铺席收费。': 'Due to random ticket distribution,upper/lower bunk tickets cannot be guaranteed when booking online. The price is a lower bunk tickets price, the actual ticket price will be charged at the time of booking. If you require guaranteed upper/lower bunks, please purchase tickets directly at the station or an authorized agent.',
    '关闭': 'Close',
    '退出失败': 'Failed to sign out',
    '请添加乘客': "Please add passenger（s）",
    '乘客最多为5人': 'Passenger  up to 5',
    '新增常旅客': 'Add new passengers',
    '编辑常旅客': 'Edit passengers',
    '还有员工未进行选座': "There are still another employee has been not selcet seat.",
    '获取审批人信息失败': 'Failed to get approver information ',
    '优先按指定座席出票，若指定座席无票，将转购其他座席': 'The system gives priority to issuing tickets to chosen seat. If there is no ticket available for the chosen seat, other seat will be booked',
    '靠窗': 'windows',
    '过道': 'aisle',
    '选择座席': 'Select position',

    // 15、	TrainOrderSureScreen.js
    '订单提交成功，查看订单还是继续预订？': 'Order submitted successfully, would you like to look over order or continue booking',
    '查看订单': 'looking over orders',
    '继续预订可能造成重复出票！确定需要预订吗？': 'Continue booking may result in duplicate ticketing! Are you sure you need to book?',
    '取消预订': "cancel booking",
    '提交订单失败出错，请重试': 'submit order erorr ,please try it again',
    '提交订单异常': 'Submit order abnormal',
    '提交订单': 'submit',
    '温馨提示': 'Tips',
    // 5、	OrderListScreen.js
    '乘客姓名/车次': 'Passenger name /train number',

    // 3、	OrderDetailScreen.js
    '违反差旅规定': 'Breach of travel regulations',
    '应付总额': 'total',
    '乘车人': 'Passenger',
    '取票单号': 'pick up ticket number',
    '车厢': 'carriages',


    // OrderRefundScreen.js
    '提交退票': 'Submit refund',
    '因公司原因行程退票': 'travel refund due to company reasons',
    '因个人原因行程退票': 'travel refund due to personal reason',
    '取消退票': 'Cancel refund',
    '确定退票': 'Confirm refund',
    '请填写改签原因': 'Please enter the reason for change',
    '提交改签成功': 'Submit change successuful',
    '提交改签失败': 'Failed to submit change',
    '提交改签异常': 'Submit change abnormal',
    '原': 'Old',
    '改': 'New',
    // 6、	OrderPaymentScreen.js
    '信息核实': 'Information review',
    '您还未完成订单支付，如现在退出，可稍后进入【个人中心】> 【机票订单】>【待付款单】页完成支付。确认退出吗': 'You haven’t finished the payment yet. If exit now, you can go to My>Domestic Flights>Pending payment to finish the payment. Are you sure to exit now',
    '您还未完成订单支付，如现在退出，可稍后进入【个人中心】> 【火车票订单】>【待付款单】页完成支付。确认退出吗': 'You haven’t finished the payment yet. If exit now, you can go to My>Trains>Pending payment to finish the payment. Are you sure to exit now',
    '继续支付': 'Continue  to pay',
    '订单确认中': 'Order confirmation',
    '获取支付数据失败': 'Failed to get payment data',
    '获取微信支付信息错误': 'Error for getting WeChat payment information',
    '获取支付宝支付信息错误': 'Error for getting AliPay information',
    '提示': 'Prompt',
    '支付失败，请重新进行支付': 'Payment failed, please repay',
    '打开微信异常': 'open wechat abnormal',
    '订单支付成功，您可去我的订单中查看': 'Successfully paid, please check it in My order',
    '共': 'Total',
    '人员信息': 'Personal information',
    '还需支付': 'Pending payment',
    '取消订单': 'Cancel the order',
    '直接支付': 'Pay now',
    '请选择支付方式': 'please selct the Payment',
    '需支付': 'Need to pay',
    '微信支付': 'WeChat payment',
    '支付宝': 'Alipay',
    '预订成功': 'Successful reservation',
    '稍后支付': 'Pay later',

    // 国内酒店
    '国内酒店': 'Domestic Hotels',

    // 10、	HotelSearchScreen.js
    '国内酒店:不限': 'Domestic hotel:unlimited',
    '我附近的酒店': 'The hotel near me',
    '定位失败': 'Location failure',
    '获取城市信息失败': 'Failed to get city information',
    '住': 'Book',
    '晚': 'night',
    '最少入住时间为1天': 'Minimum check-in time is 1 day',
    '最多允许入住20晚': 'A maximum of 20 nights is allowed',
    '(选填) 地标/商圈': '(optional) landmark/business district',

    // 5、	HotelListScreen.js
    '以上': 'Above',
    '到店支付': 'Payment to the store',
    '获取酒店列表失败请重试': 'Failed to get the hotel list please try again',
    '二星及以下': 'Three below',
    '二星级': 'Two-star',
    '一星级': 'One-star',
    '三星': 'Three star',
    '三星级': 'Three-star',
    '四星': 'Four star',
    '四星级': 'Four-star',
    '五星': 'Five star',
    '五星级': 'Five-star',
    '酒店名/地标/商圈': 'Hotel name/landmark/business circle',
    '未评定星级': 'Unrated star',
    '推荐': 'Recommend',
    '无线上网的公共区域': 'Public area of wireless Internet',
    '好评率': 'Rate',
    '暂无': 'No information',
    '暂无报价': 'No quotation',
    '酒店列表': 'Hotel list',
    '排列顺序': 'Most popular',
    '价格从低到高': 'Price from low to high',
    '价格从高到低': 'Price from high to low',
    '距离从近到远': 'Distance from near to far',
    '评论从高到低': 'Comments from high to low',
    '推荐排序': 'Most popular',
    '星级排序': 'Hotel Rating',
    '更多筛选': 'Filter',
    '价格区间': "Price range",
    '价格区间(¥)': "Price range(¥)",
    '最低价': 'Min price',
    '最高价': 'Max price',
    '星级': 'Star',

    // 11、	HotelSelectAreaScreen.js
    '获取行政区失败': 'The acquisition of the territory failed',
    '行政区': 'Area',
    '地图': 'Map',
    // 9、	HotelRoomlistScreen.js
    '酒店详情': 'Hotel information',
    '当天酒店已全部预订，请选择其它日期或者酒店': 'The hotel is fully booked on that day. Please choose another date or hotel.',
    '正在进行验价操作': 'Price checking is under way...',
    '验证价格失败': 'Failed to verify price',
    '正在检查酒店差旅规则': 'Checking hotel travel rules',
    '获取酒店差旅规则失败': 'Failed to obtain hotel travel rules',

    '一份早餐': 'A breakfast',
    '两份早餐': "Two breakfast",
    '三份早餐': 'Three breakfast',
    '无早': 'No breakfast',
    '取消政策': 'Cancellation policy',
    '免费取消': 'Free cancellation',
    '位置': 'Location',
    '入住': 'Check in',
    '可住': 'Can live',
    '离店': 'Check out',
    '层': 'F',

    // 8、	HotelOrderScreen.js
    '最少入住一间': 'At least one room',
    '每间房间至少对应一位入住人': 'Each room has at least one occupant',
    '联系人不能为空': 'Contact cannot be empty',
    '电话不能为空': 'Phone cannot be empty',
    '预计到店时间不能为空': 'The latest check-in time should not be free',
    '订单生成成功,您可去我的订单中查看': 'The order was successfully generated. You can check it in my order',
    '已存在相同酒店订单，是否继续预订?': 'hotel has already existed ,PLEASE CHECK',
    '请选择预计到店时间': 'Please choose the latest check-in time',
    '房间': 'Room',
    '选择入住人': 'Select guest',
    '每间房至少添加一人': 'Add at least one person to each room',
    '间': 'room(s)',
    '预计到店': 'Latest check-in time',
    '预计到店时间': 'Latest check-in time',
    '含早': 'include breakfast',
    '早餐': 'breakfast',
    '无早餐': 'No breakfast',


    // 7、	HotelOrderList.js
    '获取酒店列表失败': 'Failed to get the hotel list',
    '用户信息为空请退出获取': 'The user information is empty, please exit to get it',
    '酒店订单列表': 'Hotel order list',
    '入住人姓名/酒店名称/订单号': 'Name of guest/hotel/order number',
    '正在刷新数据中...': 'LOADING...',

    // 6、	HotelOrderDetail.js
    '数据请求失败': 'Data request failed',
    '加载的数据为空': 'The loaded data is empty',
    '数据加载失败': 'Data loading failure',
    '行程改变': 'Schedule change',
    '无法满足需求': 'Unable to meet demand',
    '酒店价格太贵': 'The price is too expensive',
    '其他途径预订': 'Other ways of booking',
    '其他': 'Others',
    '距离': 'Distance',
    '已提交退订': 'Unsubscribe success',
    '退订失败': "Unsubscribe failure",
    '订单取消成功': "Order cancelled successfully",
    '订单取消失败': "Order cancellation failed",
    '请输入取消的原因': 'Please enter the reason for the cancellation',
    '违反差旅规则原因': 'Cause of violation of the rules',
    '入住人': 'Check in person',
    '预订时间': 'Reservation time',
    '未填写': "Unfilled",
    '取消原因': 'Cancel the reason',

    // 4、	HotelInstrodutionScreen.js
    '基本信息': 'Basic information',
    '设施服务': 'Facilities services',
    '交通信息': 'Traffic information',
    '暂无介绍': 'No introduction',

    // 1、	HotelAddPassneger.js
    '新增入住人': 'Add check-in person',
    '请输入姓名': 'Please enter your name',

    // 3、	HotelCreditDetailScreen.js
    '信用卡信息': 'Credit card information',
    '信用卡卡号': 'Credit card number',
    '请输入信用卡卡号': 'Please enter your credit card number',
    'CVV码': 'CVV code',
    '签名栏末尾处最后三位': 'The last three digits at the end of the signature line',
    '有效年份': 'Valid year',
    '有效年份,如2020': 'Valid year, such as 2020',
    '有效月份': "Valid month",
    '有效月份,如06': 'Valid month, such as 06',
    '持卡人姓名': 'Name of cardholder',
    '请输入持卡人姓名': 'Please enter the name of the cardholder',
    '请输入持卡人证件号': "Please enter the card holder's id number",
    '请输入证件号码': 'Please enter your id number',
    '信用卡号验证失败': 'Verification failure',
    '信用卡担保失败，请重新查看': 'Credit card declied , please check again',
    '温馨提示：请确保您提供的信息与发卡行记录的信息一致': 'NOTE: Please provide you credit card information that match your credit card record',

    //国际机票

    // 6、	IndexScreen.js
    '港澳台及国际机票': 'Hongkong,Macau,Taiwan and International flights',
    '国内行程请使用（国内机票）进行购票': 'Please use domestic air tickets for domestic trips',
    '返程日期不能小于出发日期': 'The return date cannot be earlier than the departure date',
    '超值经济舱': 'Premium economy',

    // 15、	Select City Screen.js

    '请输入城市名称或三字码查询': 'Please enter the city or three - character code',
    // 7、	Low Price List Screen.JS
    '获取用户信息失败': 'Failed to get user information',
    '往返组合': 'Roundtrip combination',
    '自由选择': 'Freedom choose',
    '获取航班列表失败': 'Failed to get flight list',
    '从低到高': 'Price',
    '税': "Tax",
    '出发日期': 'Departure date',
    '返回日期': 'Date of return',
    '航班起降时间均为当地时间': 'Departure and landing time are local time',
    '没有符合条件的航班了': 'There are no eligible flights',
    '回': 'back',

    //  5、	Filter Screen.js
    '加载直飞航班': 'Loading of direct flights',
    '加载直飞航班失败': 'Failure to load direct flight',
    '加载直飞航班异常': 'Loading direct flight anomaly',
    '机场': 'Airport',
    '航空公司': "Airline",
    '起飞时段': 'Departure time',
    '抵达时段': "Arrival Time",
    '起飞': 'take off',
    '降落': 'land',
    '仅查看直飞': 'Non-stop only',

    // 8、	More Price List Screen.js
    '加载退改规则异常': 'Load Ticket Policy anomaly',
    '正在加载中': 'Loading...',
    '正在加载中...': 'Loading...',
    '获取退改规则中': 'Get in the Ticket Policy...',
    '解析退改规则异常': 'Analytic Ticket Policy anomaly',
    '航班共享信息异常': 'Flight sharing information anomaly',
    '中转': 'transfer',
    '停留': 'Stop',
    '总时长': 'Total duration',
    '选订': 'Select',
    '剩余': 'left',
    '收起': 'Pack up',
    '展开': 'Details',

    // 1、	Create Order Screen.js
    '多航段P价格': 'Multi-leg price',
    '乘客最多为9人': 'Up to 9 passengers',
    '请选择费用归属': 'Please Select Expense Attribution',
    '创建订单失败': 'Failed to create order',
    '创建订单异常': 'Create order anomaly',
    '税款': 'Tax & Fee',
    '我们为您选择的航班组合查询出更低价 ¥{{noun}}元': 'We find a lower price of {{noun}} yuan for your selected flight mix',
    // 11、	Order List Screen.js
    '订单列表': 'Order List',
    '乘客姓名／订单号': "Name of passenger/order number",
    '机票定制': 'Air ticket customization',

    // 12、	Order Refund Screen.js
    '获取订单详情异常': 'Get order details anomaly',
    '获取当前用户失败': 'Get current user failure',
    '去程': 'outbound',
    '回程': 'inbound',
    '请选择退票航班': 'Please choose a refund flight',
    '选择乘机人': 'Please Select a Passenger',
    '请填写退票的其他原因': 'Please fill in other reasons for refund',
    '提交退票成功': 'The refund was successfully submitted',
    '选择退票航班': 'Choose a refund flight',
    '航班变动': 'Flight changes',
    '选择退票原因': "Please select the reason for refund",
    '其他原因': 'Other causes',
    '其他原因（需输入原因）': 'Other causes (need to enter reasons)',

    // 13、	Order Reissue Screen.js
    '意向去程日期': 'Intended departure date',
    '意向回程日期': 'Intended return date',
    '请选择要改签的航班': 'Please select the flight you wish to change',
    '请选择乘机人': 'Please choose the passenger',
    '意向描述': 'Intention to describe',
    '原行程描述': 'Original stroke description',
    '请填写改签的其他原因': 'Please fill in other reasons for the change',
    '请选择去程意向日期': 'Please select Intended return date',
    '请选择回程意向日期': 'Please select the return intention date',
    '意向回程日期不能小于去程日期': 'Intended return date cannot earlier than the destination date',
    '请填写意向描述': 'Please fill in the Intention Description',
    '请选择去程日期': 'Please select a departure date',
    '请选择回程日期': 'Please select a return date',
    '意向日期选择': 'Choice of Intended Date',
    '选择改签航班': 'Select the flight for change',
    '选择改签原因': "Please select the reason for the change",
    '其他原因': 'Other causes',
    '（需输入原因）': '(Reasons to enter)',
    '请输入意向描述': 'Please enter the description of intention',

    // 14、	Policy View.js
    '行李说明': 'Baggage Allowance',
    '燃油': 'Fuel Surcharge',


    //港澳台及国际酒店

    // 10、	IntlHotelSearchScreen.js
    '国际酒店': 'International Hotels',
    '请选择城市': 'Select city',
    '最大入住天数不能超过28天': 'Maximum stay days should not exceed 28 days',
    '每间房间做多容纳6人': 'Each room should accommodate 6 more people',
    '（选填）地标/商圈': '(optional) landmark/business district',
    '订': 'Book',
    '获取国际酒店城市列表失败': 'Failed to get the list of international hotel cities',

    //  9、	IntlHotelSearchListScreen.js
    '国际酒店列表': 'International hotel list',
    '获取国际酒店数据失败请重试': "Failed to obtain international hotel data please try again",
    '输入酒店名称/目的地': "Enter the hotel name/destination",
    '统一结算': 'Unified payment',
    '价格钻级筛选': "Price drilling level screening",
    // 7、	IntlHotelRoomList.js
    '当天酒店已全部预定，请选择其他日期或者酒店': 'Hotel room has been sold out , please choose other rooms or hotels',

    '做多允许入住20晚': "Allow more than 20 nights to stay",
    '最大入住人数为6人': 'The maximum number of occupant is 6',
    '酒店地址': 'Hotel address',
    '酒店联系电话': "Hotel contact number",
    '人/间': "people/room(s)",
    '不含早': 'No breakfast',
    '取消政策:取消应收取': 'Cancellation policy: cancellation should be charged ',
    '元': 'RMB',
    // 3、	IntlHotelInstruction.js
    '酒店介绍': 'Hotel Introduction',
    '酒店政策': 'Hotel policy',
    // 6、	IntlHotelOrderScreen.js
    '添加其他联系人姓名(必填)': "Add the names of other contacts (Required)",
    '房型要求': 'Requirements for room type',
    '无': 'none',
    '出错了': "Error",
    '已经超出了最大入住人数': 'Exceeded the maximum number of residents',
    '每间房间至少对应以一位入住人': "Each room should have at least one guest",
    '请完善英文名称': 'Please fill out all the information',
    '联系人名称不能为空': 'The contact name cannot be empty',
    '联系人电话不能为空': 'Contact Numbers should not be empty',
    '电子邮件不能为空': 'Email cannot be empty',
    '可入住': 'available',
    '请选择(必填)': 'Please select (Required)',
    '请选择(选填)': 'Please select (optional)',
    '电话号码(必填)': 'Telephone number(Required)',
    '电子邮件(必填)': 'Email (required)',
    '下单后取消将扣除': 'Cancellation will be deducted after placing the order ',
    '在{{noun}}之前取消免费,之后取消收取': 'No charge until {{noun}} and then charge ',
    '在{{noun}}之后取消收取': 'after {{noun}}，will charge ',
    // 8、	IntlHotelRoomRequire.js
    '尽量安排无烟房': 'None-smoking room',
    '房型': "room",
    '如果有其他要求请填写,酒店会尽量安排': 'PLEASE WRITE DONE YOUR Requirement, WILL SEND HOTEL',
    ' FCM商旅会把您的要求转达酒店，但不能保证酒店一定可以满足，如有特殊要求，请自行联系酒店': ' ALL THE REQURMENT WILL DEPANDING ON THE HOTEL , IF YOU HAVE PERSONAL REQURMENT PLEASE CONTACT HOTEL',
    // 1、	IntlHotelAddPassenger.js
    '姓(英)': 'First name',
    '名(英)': 'Last name',
    '如': 'example',
    //  5、	IntlHotelOrderList.js
    // ''
    // 4、	IntlHotelOrderDetail.js
    '因公司原因取消订单': "Cancel the order for company reasons",
    '因个人原因取消订单': 'Cancel the order for personal reasons',
    '其他(需要输入原因)': 'Others (need to input reasons)',
    '取消规则': 'Cancellation policy',
    '应付金额': 'Payable',
    '其它': 'Others',
    '请输入取消原因': 'Please enter the cancellation reason',
    '下单后取消将扣除{{noun}}元': '{{noun}} yuan will be deducted if the order is cancelled',
    '在{{noun}}之前取消免费': 'before {{noun}} cancel free',
    '之后取消收取': 'after cacel ',
    '在{{noun}}之后取消收取': 'after {{noun}} cancel',
    '酒店电话': 'Hotel phone',
    //用车

    //  10、	CarSearchScreen.js

    '请选择出发地点': 'please select pick-up Location',
    '请选择送达地点': 'please select Drop-off Location',
    '请填写航班号(选填)': 'Please fill in the flight number (optional)',
    '请填写航班号(必填)': 'Please fill in the flight number (required)',
    '接送机': 'Airport transfer',
    '滴滴打车': 'Didi taxi',
    '请选择用车时间': 'please select Pick-up Date and Drop-off Date',
    '送达地点': 'Drop-off Location',
    '出发地点': 'Pick-up Location',
    '接机': 'Pick up',
    '送机': 'Send machine',
    '未开通用车功能': 'unopened car function',
    '请选择航班': 'plsease select flight',
    '出发地不能为空': 'Departure cannot be empty',
    '目的地不能为空': "Destination cannot be empty",
    '距离用车时间1小时以上可预订': 'Car reservation can be booked for more than 1 hour',
    '能预订最长30天以内的用车': 'can book a car for up to 30 days',
    '航站楼信息有误，请点击航站楼重新进行选择': 'Terminal information is wrong. Please click the terminal to re-select',
    '我的航班': "My flight",
    '可预订1小时后行程': 'can book a trip after one hour',
    //  9、	CarPlace.js

    '正在获取当前位置>>>': 'getting location',
    '未能获取当前位置': 'failed to get location',
    '请输入地点': 'please enter addrss',
    '搜索的位置': 'Search location',
    '当前位置': 'location',
    '历史记录': 'history record',

    // 1、	CarAirport.js
    '机场选择': 'Airport preference',
    '请求数据失败请重试': 'failed to request data please try again',
    '历史城市': 'History city',
    '城市机场': "City airport",
    '请输入机场名/三字码': "please enter airport name/three code",
    // 4、	CarMyFlight.js
    '获取订单列表失败，请重新尝试': 'Failed to get the order list, please try again',
    '获取订单列表失败': 'Failed to get the order list',
    '至': 'to',
    //  3、	CarList.js
    '车型选择': 'Car type selection',
    '抱歉，查询无结果': 'sorry ,Inquire no result',
    '终于回来了，价格可能有变化，将为您重新查询': 'Finally came back, the price may have changed and we will be re-search for you',
    '所有车型': 'all type',
    '经济型': 'Economy',
    '大众宝来、别克凯越等同级车': 'Volkswagen bora、 buick excelle or similar',
    '舒适型': "comfort",
    '大众帕萨特、本田雅阁等同级车': 'Volkswagen Passat honda Accord  or similar',
    '商务型': 'bussniss',
    '别克GL8、本田奥德赛等同级车': 'buick GL8 honda  Odyssey  or similar',
    '豪华型': 'Luxury',
    '奢华型': 'Luxury',
    '宝马7系、奔驰S350等同级车': 'BMW 7 Series、Mercedes Benz S350 or similar',
    '8座小巴': '8 buses',
    '丰田海狮等同级车': 'Toyota hiace or similar',
    '10座小巴': '10 buses',
    '丰田海狮、全顺面包、奔驰MB100等同级车': 'Toyota hiace   transit  van  Mercedes Benz MB100 or similar',
    '15座中巴': '15 buses',
    '宇通、金龙等同级车': 'Yutong  Golden Dragon or similar',
    '20座中巴': '20 buses',
    '小金龙、考斯特等同级车': 'Little golden dragon,coster or similar',
    '金龙等同级车': 'Golden Dragon or similar',
    '30座中巴': '30 buses',
    '35座中巴': "35 buses",
    '金龙中巴、宇通中巴等同级车': 'Golden Dragon 、Yutong  or similar',
    '40座中巴': '40 buses',
    '45座大巴': '45 buses',
    '50座大巴': '50 buses',
    '大金龙宇通等同级车': 'Golden Dragon  Yutong or similar',
    '53座大巴': '53 buses',
    '金龙宇通等同级车': 'Golden Dragon  Yutong or similar',
    '奥迪A6L等同级车': 'Audi A6L or similar',

    //  8、	CarOrderScreen.js
    '请添加乘车人': 'please add passenger',
    '预订人手机号不能为空': 'The reservation number cannot be empty',
    '生成订单失败': 'Failed to generate order',
    '获取预订须知': "get booking Information",
    '获取预订须知失败': 'failed to get booking Information',
    '预订须知': 'Booking Information',
    // 7、	CarOrderNotice.js
    '乘车须知': "passenger notice",
    '计费规则': 'billing Rules',
    // 6、	CarOrderList.js
    '用车订单列表': 'Car list',
    '始': 'star',
    '终': 'end',
    // 5、	CarOrderDetail.js
    '与司机达成一致': 'Agreement with the driver',
    '司机爽约': 'The driver to break a promise',
    '司机要求我支付现金': 'Driver asked me to pay cash',
    '司机电话联系我取消订单': 'The driver contacted me to cancel the order',
    '司机说车坏了': 'The driver said the car was broken',
    '司机订单冲突': 'order confict',
    '请选择取消原因': 'Please choose the reason for cancellation',
    '个人原因': 'Personal reasons',
    '航班延误或取消': 'Flight is delayed or cancelled',
    '司机原因': 'The driver causes',
    '取消订单出现错误': 'Error cancelling order',
    '公里数': 'kilometers',
    '公里': 'kilometers',
    '行驶': 'Driving',
    '分钟': 'minutes',
    '退订规则': 'Unsubscribe rules',
    '司机': 'driver',
    '车牌号': 'license plate number',
    '已提交': 'submitted',
    '已派单': 'Dispatched',
    '确认中': 'In the confirmation',
    '司机行驶中': 'Driver is driving',
    '司机已到达': 'Driver has arrived',
    '已经加载完全部': 'Load all',
    '30分钟后未派单，平台自动取消订单': 'The platform will cancel the order automatically after 30 minutes',

    //补充
    '您有未支付订单，需要先完成支付。': 'You have an unpaid order and need to complete the payment first.',
    '稍后处理': 'Later processing',
    '去支付': 'To pay for',
    '是否重新获取': 'Is it reacquired',
    '确定退出登录么？': 'Are you sure to log out?',
    '出差申请': 'Travel request',
    // '出差申请':
    '乘客姓名／车次': 'Passenger name/train number',
    '登录失效,请重新登录': 'Login failed, please login again',
    //ohter

    //    1、	HomeScreen.js

    '提升用户体验': 'Improve user experience',
    '去升级': 'Update',
    '忽略': 'Ignore',
    '收起': 'Details',
    '展开': 'Details',
    '您当前登录账户为测试环境，仅作为流程演示，如需真实预订请在【我的】页面中联系客服！': 'Your current login account is in the testing environment only for process demonstration. Please contact customer service in the "Mine" page for actual reservation!',
    '位置查看': 'View location',
    '联系酒店': 'Contact the hotel',
    '未开通国内机票功能': "Domestic Flights function unavailable",
    '未空通国际机票功能': 'International flight ticket function unavailable',
    '未开通国际酒店功能': 'International hotel function unavailable',
    '未开通火车票功能': "Train ticket function unavailable",
    '未开通国内酒店功能': 'Domestic hotel function unavailable',
    '因公预订': 'Business Trip',
    '因私预订': 'Personal Trip',
    '用车': 'Car Service',
    '您好': 'Hello',
    '首页': 'Home',
    //    2、	FlightJourneyItem.js
    '订票单': 'Ticketed',
    '改签单': 'Exchanged',
    '退票单': 'Refund',
    '(因私)': '(Private)',
    '(因公)': '(Business)',
    '入住时间': 'Check-in time',
    '离店时间': 'Check-out time',
    '因公司原因': 'Company reasons',
    '因航班变动': 'Flight changes',
    '因个人原因': 'Personal reasons',
    // 5、	JourneyScreen.js
    '行程': 'Schedule',
    '未出行订单': 'In Plan Schedule',
    '详情': 'Details',
    '没有找到符合条件的数据': "No eligible data found",
    '没有更多数据了': 'No more data',
    '没有更多数据了...': 'No more data...',
    '获取行程列表失败': 'Failed to get journey list',
    '正在获取用户信息中': 'Getting more user information',
    '上拉加载更多': 'Pull up to load more',
    '航班号': 'Flight number',
    '订单号': 'Order number',
    '车次': 'Train number',
    '酒店名称': 'Hotel name',
    '入住人姓名': "Name of the resident",
    '乘客姓名': 'Name of the passenger',
    // 6、	ForgetPwdScreen1.js
    '验证': 'Verify',
    '联系客服': 'Contact customer service',
    '忘记密码': 'Forgot password',
    '忘记密码?': 'Forgot?',
    '手机号不能为空': 'Mobile number cannot be empty',
    '{{noun}}手机号不能为空': '{{noun}} Mobile number cannot be empty',
    '获取验证码': 'Verify',
    '获取验证码失败': 'Failed to get the verification code',
    '验证码不能为空': 'The verification code cannot be empty',
    '验证码不正确': 'The verification code is incorrect',
    '验证码校验失败': 'Failed to verify the verification code',
    '请填写手机号': 'Please fill in the mobile number',
    '请输入验证码': 'Please enter the verification code',
    '入住日期': 'Check-in date',
    '下一步': 'Next',
    '1': 'first',
    '2': 'second',
    '3': 'third',
    '4': 'fourth',
    '5': 'fifth',
    '第{{noun}}位员工姓名不能为空': "The {{noun}} employee's name cannot be blank",
    '第{{noun}}位员工手机号不能为空': "The {{noun}} employee's mobile phone number cannot be empty",
    '第{{noun}}位员工证件信息不完整': 'The id information of {{noun}} employee is incomplete',
    '第{{noun}}位常用旅客姓名不能为空': "The {{noun}} common passenger's name cannot be blank",
    '第{{noun}}位常用旅客手机号不能为空': 'The mobile phone number of the {{noun}} frequent passenger cannot be empty',
    "第{{noun}}位常用旅客证件信息不完整": "The {{noun}} frequently used passenger's identification information is incomplete",
    '第{{noun}}位乘客的信息异常': "The {{noun}} passenger's information is abnormal",
    '第{{noun}}位乘客的姓名未填': "The name of the {{noun}} passenger has not been filled in",
    '{{noun}}的英文姓未填': 'The English surname of {{noun}} remains unfilled',
    '{{noun}}的英文名未填': 'The English name of {{noun}} has not yet been filled in',
    '{{noun}}的手机号未填': 'The phone number {{noun}} has not been filled in yet',
    '{{noun}}的国籍未填': 'The nationality of {{noun}} has not yet been filled',
    '{{noun}}的证件类型未选': "{{noun}} id type is not selected",
    '{{noun}}的证件号码未填': 'The document number {{noun}} has not been filled in',
    '{{noun}}的证件有效期未选': '{{noun}} certificate is not valid',
    '{{noun}}的性别未选': "{{noun} gender is not selected",
    '{{noun}}的生日未填': "The birthday of {{noun}} has not yet been filled in",
    // 7、	ForgetPwdScreen2.js
    '请输入新密码': 'Please enter a new password',
    '请再次输入密码': "Please re-enter the password",
    '两次输入不一致': 'Two passwords are not match',
    '密码重置成功': 'Successfully reset the password',
    '密码重置失败': 'Failed to reset the password',
    '重置密码异常': 'Exception of password resetting',
    //   8、	LoginScreen.js
    '正在获取用户信息': 'Getting user information',
    '客户编号不能为空': 'Customer number cannot be empty',
    '用户名不能为空': 'User name cannot be empty',
    '密码不能为空': 'The password cannot be empty',
    '登录失败': "Login failed",
    '客户编号': "Customer number",
    '工号/邮箱/手机号': "Job number/Email/Mobile number",
    '请输入登录账号': 'Please enter your login account',
    '请输入密码': 'Please enter the password',
    '指定客户编号登录': "Specified customer number login",
    '登录': 'Sign in',
    '注册': 'Register',
    '登录中': 'Log in',
    // 9、	RegisterScreen.js
    '注册企业账号': 'Register enterprise account',
    'FCM企业商旅服务条款': 'Terms of service',
    '企业名称不能为空': 'The enterprise name cannot be empty',
    '姓名不能为空': 'Name cannot be empty',
    '邮箱不能为空': "Email cannot be empty",
    '邮箱格式不正确': "Email form is incorrect",
    '注册成功，客服人员将会尽快和您联系，请保持电话畅通～': 'Successfully registered. The customer service staff will contact with you as soon as possible. Please keep your phone available~',
    '注册提交失败，请联系客服处理': 'Registration failed, please contact customer service.',
    '如果贵公司已签约为FCM商旅客户，请联系差旅负责人获得个人登录账号，请勿重复注册': 'If your company has signed up for On-the-journey Business Travel, please don’t repeat registering and contact with the responsible person for on-business travel to get individual login account.',
    '企业名称': 'Enterprise name',
    '所在公司名称': 'Name of the working company',
    '中文/英文名': 'Chinese/English name',
    '常用邮箱地址': 'Frequently used email address',
    '手机号输入': 'Enter the mobile number',
    '4位/6位数字': '4-digit/6-digit number',
    '点击注册表示同意': 'Click Register to agree',
    '验证码': 'Verification code',
    '《FCM商旅服务条款》': '"FCM Business Travel Service Terms"',
    // 10、	ApprovalScreen.js
    '审批': 'Approval',
    // 10、	ApprovalScreen.js
    '待我审批': 'Pending Approval',
    '审批完成': 'Finished Approval',
    '确定同意批准该订单么？': 'Are you sure to approve the order now?',
    '审批成功': 'Successfully approved',
    '审批失败，请联系客服': 'Approval failed, please contact customer service',
    '审批异常，请联系客服': 'Approval exception, please contact customer service',
    '获取审批列表失败': 'Failed to get the approval list',
    '跳过': 'Skip',
    '请选择申请单': 'Please select the application form',
    '申请单': 'Application form',
    '申请单号': 'Serial number',
    '提交日期': 'Submission date',
    // 11、	FlightApprovalItem.js
    '驳回': 'Reject',
    '同意': 'Approve',
    '出差人姓名': 'Name of business traveler',
    // 14、	ActionSheet.js
    '卖出': 'Sell',
    '买入': 'Buy',
    // 17、	App.js
    '再按一次返回键退出本应用': 'Press the return button again to exit the APP',
    // 18、	Calendar.js
    '日期选择': 'Date selection',
    '今天': 'Today',
    // 19、	FetchHelper.js
    '网络超时，请检查您的网络': 'Network timeout, please check your network connection',
    '发生异常': 'Abnormal',
    // 20、	RuleView.js
    '已减': 'Saved ',
    '特惠价': "Lowest price",
    '大客户': 'Key Account',
    "优惠产品": "Promotion",
    // 21、	BaseView.js
    '温馨提示': 'Notice',
    '登录失败，请重新登录': 'Login failed, please login again',
    '仅限一个预订人': 'Only for a single booking person',
    '审批驳回': 'Reject',
    '审批通过': 'Approve',

    // 25、	PassengerView.js
    '加载常旅客失败，请重新加载': 'Failed to load the frequent passenger, please reload',
    '亲，没有符合条件的乘客啦': 'Oh, there is no more eligible passenger',

    // 26、	PaySureScreen.js
    '取消订单异常': 'Exception of order canceling',
    '订单支付失败，请重新进行支付': 'Payment failed, please try again',
    '乘机人信息': 'Information of airplane passengers',
    '订单金额': 'Order amount',
    '支付信息': 'Payment information',
    '春秋航空附加产品': 'Additional products of Spring Airlines',
    '航班': 'Flight',
    // 27、	ProjectListScreen.js
    '数据加载失败请重试': 'Failed to load data, please try again',
    '选择项目': 'Select projects',
    '输入不足6个字符不符合查询条件': 'Entered less than 6 characters mismatching the query conditions',
    '输入项目名称': 'Please enter the project name',
    '输入名称': 'Please enter the name',
    // 28、	ReuisitionSelect.js
    '获取申请单列表失败': 'Failed to get the application list',
    '您确定要继续预订吗': 'Are you sure to continue the reservation?',
    '根据贵公司差旅政策规定，因您未选择最低价航班，故请您选择原因:': 'According to your company’s business travel policies, as you haven’t selected a flight with the lowest price, please select your reason:',

    //日期

    // ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'];
    '陪同领导或者客户': 'Accompany the leader or client',
    '出发或到达时间不合适': "The departure state and arrival time are not suitable",
    '原定出差计划临时变更': 'Temporary change of original business trip plan',
    '得到特别授权': 'Under special authority',
    '已无其他座位可预定': 'There are no seats available for other optional seats',
    '车站选择': 'The station choose',
    '计划外的紧急出差任务': 'An unscheduled emergency business trip',
    '两人同住分摊房费': 'Shared by two person',
    '当地无标准内饭店': 'No hotel within standard in the city',
    '为客户预定/招待客户': 'Reservation for client',
    '节假日或者展会期间房价上涨': 'Increasing rate during Holidays or Exhibition',
    '经批准可不受政策限制': 'Authorized,no policy restrictions',
    '会议或培训等活动指定酒店': 'Appointed hotel of meeting or training,etc',
    '超标费用自行承担': 'The extra amount on personal expense',
    /**
     * 订单状态
     *
     */
    '审批中': 'Under approval',
    '待审批': 'Approval Pending',
    '已出票': 'Ticket issued',
    '已驳回': 'Rejected',
    '退票中': 'Refunding',
    '已退票': 'Refunded',
    '改签中': 'Changing',
    '已改签': 'changed',
    '已取消': 'Cancelled',
    '出票失败': 'Failure',
    '待付款': 'Pending payment',
    '已支付': 'Already paid',
    '占座中': 'Holding a Seat',
    '占座成功': 'Occupy success',
    '待担保': 'To be guaranteed',
    '预订中': 'To be Reserve',
    '待确认': 'To be confirmed',
    '已确认': 'Confirmed',
    '已入住': 'Checked In',
    '取消中': ' To be cancel',
    '已退订': 'Cancelled',
    '自签酒店预订中': "Self signed hotel reservation",
    '退订中': 'Unsubscribe',
    '预订失败': 'Reservation failure',
    '已满房': 'Full',
    '预订成功': 'Reservation canfirmed',
    '待预订': 'To be reserved',
    '已离店': 'Checked out',
    '未入住': 'No Show',
    '出票中': 'Ticketing',
    '占座失败': 'Take Seat Failure',
    '退票失败': 'Cancellation Failure',
    '改签失败': 'Change Failure',
    '待处理': 'Pending',
    '已处理': 'Already processed',
    '司机服务完成': 'Completion of driver service',
    '已完成': 'Confirm',
    '有效': 'effective',

    '由于铁路局规定，距离开车前48小时以内，您的车票不允许提交变更到站': 'Due to the regulations of the Railway Administration, your ticket is not allowed to submit changes to the station within 48 hours before driving.',
    '由于铁路局规定，您的车票只能改签当天的列车': 'Due to the regulations of the railway bureau, your ticket can only be changed to the train on the day.',
    '由于铁路局规定，您的车票只能改签到票面日期当日以及票面日前之前的列车': 'Due to the regulations of the Railway Administration, your ticket can only be changed to the train date and the train before the ticket date.',
    '获取退票费失败': 'Obtaining abnormality of refund fee',
    '提交退票将产生退票费用¥{{noun}},是否继续提交退票?': 'Submitting a refund will result in a refund fee of ¥{{noun}}. Will it continue to submit the refund?',
    '(实际退票费用以航司退款金额为准)': '(the actual refund will be used for refund by the airline)',
    '经停站': 'Route Info',
    '全程': 'Total duration',
    '获取经停数据异常': 'Gets the stopped data exception',
    '停': 'Stop',
    '定位服务未开启': 'The location service is not enabled',
    '暂不': 'Temporarily not',
    '去设置': 'To set up',
    '请在系统设置中开启定位服务': 'Open the location service in the system Settings',
    '保险产品': 'Insurance products',
    '请选择国籍': 'Please select nationality',
    '请选择证件签发国': 'Please select the issuing country',
    '证件签发国': "Issuing country",
    '选择国家/地区': 'Select country',
    '获取国家数据失败': 'Failed to access national data',
    '获取国家数据异常': 'Obtain national data exceptions',
    '{{noun}}的证件签发国没填写': '{{noun}} issuing country did not fill out',
    '电子行程单': 'Electronic itinerary',
    '页数': 'page',
    '比例': 'scale',
    '是': "yes",
    '否': 'no',
    '横屏': 'Horizontal',
    '电子行程单 查看': 'Electronic itinerary check',
    '退订日期:': 'Unsubscribe date:',
    '退订入住人:': 'Unsubscribe:',
    '退票费:': 'Refund fee:',
    '房费:': 'The room rate:',
    '提交时间:': 'Submission time:',
    '全部酒店': 'All',
    '自签酒店': 'SelfSigned',
    '协议酒店': 'Agreement',
    '退订费': 'Unsubscribe',

    // 会奖旅游
    '会奖旅游': 'MICE',
    '酒店': 'Hotels',
    '实际由': 'Actually by',
    '承运': 'Shipment',
    '省/市/区': 'province/city/area',
    '删除': 'delete',

    '行程管理': 'My Bookings',
    '差旅预订': 'New Booking',
    '发票申请': 'Request invoice',
    '发票邮寄': 'Send invoice',
    '差旅报告': 'Travel report',
    '确定要退出登录吗?': 'Are you sure you want to log out?',
    '切换语言成功': 'Language switched successfully',

    '退出登录': 'Log Out',
    '动态密码': 'Dynamic password',
    '勾选并同意': 'Sign in for consent',
    '请填写绑定的手机号': 'Please fill in the bound mobile number',
    '更多': 'More',
    '明天': 'Tomorrow',
    '今天': 'Today',
    '后天': 'The day after tomorrow',
    '历史准点率': 'Historical punctuality rate',
    '当日最低': 'Lowest fare',
    '实际起飞时间': 'Actual takeoff time',
    '退改规则': 'Ticket policy',
    '隐藏共享': 'Hide code-share flights',
    '航司官网': 'Navigation official website',
    '航司旗舰店': 'Airline Direct',
    '经济舱最低价': 'Economy class lowest price',
    '公务舱最低价': 'Business class lowest price',
    '头等舱最低价': 'Business class lowest price',
    '距离市区46公里，搭乘地铁到市区（草桥站）需约30分钟': "It's 46 kilometers away from the city. It takes about 30 minutes to get to the city (Caoqiao station) by subway",
    '为其他员工预订': 'Book for other employees',
    '为常旅客预订(非员工)': 'Book for frequent flyer (non employee)',
    '台湾居民来往大陆通行证': 'Travel Permit for Taiwan Residents',
    '港澳居民来往内地通行证': 'Travel Permit for Hong Kong and Macao Residents',
    '注：乘客已关联员工身份，若为其他人预订请返回上页添加员工或常旅客': 'Note: Booking for another person, please return to the previous page to add an employee or frequent flyer info',
    '乘客姓名/入住人姓名/订单号': "Traveler's Name/order number",
    '新申请': 'New Request',
    '因任何原因需要进行的退改签机票（包含因客观原因导致的航班取消），须自行通过订票系统或拨打400-8109-777进行退改签操作处理': 'Passengers shall use this system or call 021-22111889 for ticket changing or cancellation (including flight cancellation due to objective reasons).',
    '等待投保': 'Waiting for insurance',
    '起飞': 'Take off',
    '含税': 'Tax Incl',
    '不含税': 'Tax Excl',
    '往返价': 'Round-trip price',
    '航班': 'flight',
    '直飞': 'non-stop flight',
    '若您未按照订单中的航班顺序乘坐，将自行承担航班无法登机的所有风险和责任；': 'if you do not take the flight in the order, you will bear all the risks and responsibilities of the flight being unable to board;',
    '大陆乘客来往香港，请使用港澳通行证；使用护照出行的乘客，须同时持有7天内前往第三国或地区的机票；': "For mainland passengers travelling to and from Hong Kong, please use the Hong Kong and Macao pass; for passengers travelling with passports, they must hold a ticket to a third country or region within 7 days;",
    '大陆乘客来往台湾，证件类型请使用台湾通行证，如在台湾中转/经停，请选择护照并携带后续航班行程单；': "For mainland passengers travelling to and from Taiwan, please use Taiwan pass for the type of certificate. For transit / stopover in Taiwan, please select passport and carry the itinerary of subsequent flights;",
    '乘客姓名/订单号': 'Passenger name / order number',
    '立即叫车': 'Call a car',
    '预约用车': 'Appointment car',
    '您在哪下车': 'Where do you get off',
    '正在获取当前位置...': 'Getting current location...',
    '附近暂无可用车辆，请稍后再试': 'No vehicles are available nearby. Please try again later',
    '请输入详细地点': 'Please enter the detailed location',
    '公司旅游': 'Corporate Tourism',
    '公司会议': 'Company meeting',
    '出发地': 'Departure',
    '目的地': 'Destination',
    '出行人数': 'Number of passengers',
    '人均预算': 'Per capita budget',
    '请输入人数': 'Please enter the number of people',
    '请输入人均预算': 'Please enter per capita budget',
    '请输入联系人': 'Please enter contact',
    '元/人': '¥/person',
    '出行日期': 'Travel date',
    '会议地点': 'Meeting place',
    '参会人数': 'Number of participants',
    '请选择会议所在城市': 'Please enter the city of the meeting',
    '请输入参会人数': 'Please enter the number of participants',
    '会议预算': 'Conference budget',
    '请输入预算金额': 'Please enter budget amount',
    '请输入联系人姓名': 'Please enter contact',
    '会议日期': 'Meeting date',
    '未使用机票': 'Unused air tickets',
    '关于我们': 'About us',
    '关注商旅公众号': 'Official account of business travel',
    '个人差旅报告': 'Personal travel report',
    '部门差旅报告': 'Department travel report',
    '项目差旅报告': 'Project Travel Report',
    '出差费用': 'Travel expenses',
    '出差分析': 'Travel analysis',
    '该时间段无差旅数据': 'No travel data for this period',
    '该时间段无违反差标损失': 'There is no violation of differential standard loss in this period',
    '该时间段无违反差标订单': 'There is no violation of differential order in this period',
    '差旅费用': 'Travel expenses',
    '分类': 'sort',
    '月份': 'month',
    '发票邮寄单': 'Invoice mailing list',
    '配送方式': 'Delivery',
    '请选择配送方式': 'Please select delivery method',
    '在线支付': 'Prepay online',
    '税号': 'Tax number',
    '地址': 'Address',
    '发票抬头': 'Invoice Header',
    '快递费': 'Express fee',
    '在线支付订单行程单(发票)申请': 'Online payment order itinerary (invoice) application',
    '开发票': 'Draw a bill',
    '待支付': 'To be paid',
    '电子发票': 'Electronic invoice',
    '纸质发票': 'Paper invoice',
    '申请日期': 'Date of application',
    '开票中': 'Invoicing',
    '费用明细': 'Details of expenses',
    '乘客姓名/订单编号': 'Passenger name / order number',
    '机票': 'Plane ticket',
    '查询详情': 'Query details',
    '行程日期': 'Itinerary date',
    '订单编号': 'Order number',
    '开具发票': 'Invoicing',
    '请选择发票类型': 'Please select invoice type',
    '注：电子发票仅支持普通发票': 'Note: e-invoice only supports general invoice',
    '发票详情': 'Invoice details',
    '抬头类型': 'Head up type',
    '企业': 'enterprise',
    '个人': 'personal',
    '非企业': 'Non enterprise',
    '请选择发票抬头': 'Please select invoice header',
    '请输入税号': 'Please enter tax number',
    '单位地址': 'Unit address',
    '请输入单位地址': 'Please enter company address',
    '开户银行': 'Bank of deposit',
    '请输入开户银行名称': 'Please enter the Bank of deposit',
    '银行账户': 'Bank account',
    '请输入银行账户': 'Please enter bank account',
    '接收方式': 'Receiving mode',
    '电子邮箱': 'Mail box',
    '请输入电子邮箱': 'Please enter email',
    '收件人': 'Addressee',
    '请输入收件人': 'Please enter the recipient',
    '请输入联系方式': 'Please enter contact information',
    '发票金额': 'Invoice amount',
    '当订单中包含退票订单，退票费发票为增值税普通发票': 'When the order contains a dishonor order, the dishonor fee invoice is a general VAT invoice',
    '机票行程单+服务费（专票）': 'Ticket itinerary + service charge (special ticket)',
    '机票行程单+服务费（普票）': 'Air ticket itinerary + service charge (general ticket)',
    '详细地址': 'Detailed address',
    '请选择详细地址': 'Please select a detailed address',
    '查看': 'See',
    '发票内容': 'Invoice contents',
    '开票时间': 'Billing time',
    '添加邮寄地址': 'Add mailing address',
    '选择配送地址': 'Select shipping address',
    '联系电话': 'Contact number',
    '所在地区': 'Location',
    '保存并使用': 'Save and use',
    '编辑配送地址': 'Edit shipping address',
    '国内/国际行程': 'Domestic / International Travel',
    '行程类型': 'One way roundtrip',
    '预订产品': 'Booking products',
    '优先登机': 'Priority boarding',
    '根据公司差旅政策，推荐您预订低价航班': 'Suggest to book flight with lowest fare according to company travel policy.',
    '预订最低价': ' Book flight with lowest fare',
    '继续预订原航班': 'Continue booking this flight',
    '根据贵公司差旅政策规定，您选择的时间段内的最低价航班为：': 'The following flight is suggested for bookable flight according to company travel policy.',
    '未选择最低价': ' Out-of-policy Reason',
    'OA单号': 'OA No.',
    '支付方式': 'Payment method',
    '企业月结': 'To be paid by Company',
    '民航基金': 'Civil Aviation Fund',
    '点击创建表示同意': 'Click “Create Order” means passengers agree to follow ',
    '港澳台居民居住证': 'Residence permit for Hong Kong, Macao and Taiwan residents',
    '外国人永久居留身份证': 'Foreigner Permanent Resident ID Card',
    '{{noun}}航班': '{{noun}} flights in total',
    '中转城市': 'Transfer cities',
    '选择席位': 'Select seats',
    '请输入票抬头': 'Please enter invoice header',
    '自行领取(航班起飞后2个工作日到一楼大厅售票处领取)': 'Self pick-up (From airport terminal in 2 working days after taking off)',
    '顺丰(顺丰速运)': 'Express delivery (Shunfeng)',
    '中通(中通快递)': 'Express delivery (Zhongtong)',
    '价格信息': 'Expense Details',
    '自愿改期将按照航空公司改签规则收费，请确认是否继续提交?': 'Change fee will be charged according to ticket policy. Please confirm whether to proceed.',
    '大客户政策': 'Key Account',
    '授权人': 'Authorized Person',
    '配送信息': 'Delivery Address',
    '最低价规则': 'Out-of-policy reason',
    '行程类型': 'Trip Type',
    '费用预算': 'Budget',
    '研发部': 'R&D',
    '请输入驳回原因': 'Please fill in reasons for rejection',
    '驳回原因不能为空': 'Please fill in reasons for rejection',
    '接受无座': 'Accept standing ticket',
    '部门': 'Department',
    '项目': 'Project',
    '车票': 'Ticket Price',
    '钱包支付':' Pay from company account',
    '超标现付':'Personal payment for overbudget portion',

    //FCM 5月20日
    '请填写费用预算':'Please fill in the expense budget',
    '结算主体':'Settlement of invoice / Settlement entity',
    '结算方式':'Method of Payment',
    '行李及退改规则':'Baggage and refund and re-issue/change guidelines',
    '请填写超标原因':'Please state reasons for exceeding the criteria',//placeholder
    '催审成功':'Urgent approval is successsful',
    '开票历史':'Ticketing history',
    '邮寄详情':'Mailing details',//title
    '邮寄业务':'Mailing',//title
    '保险信息':'Insurance information',
    '动态密码登录':'One-Time Password Login',//title
    '《隐私协议》':'Privacy policy',
    '《服务条款》':'Service agreement',
    '如果订单中包含保险订单，保险订单为定额发票':'If the order includes insurance, the insurance order will be billed as a fixed amount',
    //综合订单  自由翻译测试
    '继续预订':'Continue booking',
    '统一支付':"On account",
    '到店支付':'Pay on arrival',
    '不限':'All',
     '统一支付 到店支付 不限':'On account Pay on arrival All',
    "大床":'Double Bed',
    "双床":"Twin Beds",
    "担保":"Guaranteed",
    '大床 双床 不限':'Double Bed Twin Beds All',
    "到店现付":"Pay on arrival",
    "已关联":"Signed-in",
    "切换":"Switch account",
    '已关联/切换':'Signed-in/Switch account',
    '已关联...':'Signed-in...',
    '重新关联':'Re Signed-in',
    '关联中':'Signed-in',
    '关联中...':'Signed-in...',
    '切换/退出12306':'Re associate switch / exit 12306',
    '用户名':'user name',
    '12306用户名/邮箱/手机号':"12306 user name / email / mobile number",
    '密    码':'password',
    '12306密码，非FCM账号密码':'12306 password, non FCM account password',
    '核验码':'Verification code',
    '发送短信666到12306获取':'Send SMS 666 to 12306 for',
    '记住账号密码':'Remember the account password',
    '登录12306':'Login 12306',
    '退出账号':'Exit account',
    '关联':'relation',
    '铁路局规定购票必须实名制':'The Railway Bureau stipulates that tickets must be purchased under the real name system',
    '登录12306账号提高出票成功率':'Log in to 12306 account to improve the success rate of ticket issuance',
    '飞机票':'Air ticket',
    '起':'From',
     '订完':'Finished Booking',
     "预订政策":'Terms and conditions for booking'
    // '检测到该设备存在安全风险':
    //================================================================================//

    
    // 因任何原因需要进行的退改签机票（包含因客观原因导致的航班取消）电话替换成变量
    //--------------------------------------------------------------------------------//
    
    






}