const TrainHotData = [
   {
        "Name": "北京",
        "EnName": "BEIJING",
        "Code": "BJP",
        "Spell": "BJ|BEIJING"
    },
    {
        "Name": "上海",
        "EnName": "SHANGHAI",
        "Code": "SHH",
        "Spell": "SH|SHANGHAI"
    }, {
        "Name": "天津",
        "EnName": "TIANJIN",
        "Code": "TJP",
        "Spell": "TJ|TIANJIN"
    }, {
        "Name": "重庆",
        "EnName": "CHONGQING",
        "Code": "CQW",
        "Spell": "CQ|CHONGQING"
    }, {
        "Name": "长沙",
        "EnName": "CHANGSHA",
        "Code": "CSQ",
        "Spell": "CS|CHANGSHA"
    }, {
        "Name": "长春",
        "EnName": "CHANGCHUN",
        "Code": "CCT",
        "Spell": "CC|CHANGCHUN"
    }, {
        "Name": "成都",
        "EnName": "CHENGDU",
        "Code": "CDW",
        "Spell": "CD|CHENGDU"
    }, {
        "Name": "福州",
        "EnName": "FUZHOU",
        "Code": "FZS",
        "Spell": "FZ|FUZHOU"
    }, {
        "Name": "广州",
        "EnName": "GUANGZHOU",
        "Code": "GZQ",
        "Spell": "GZ|GUANGZHOU"
    }, {
        "Name": "贵阳",
        "EnName": "GUIYANG",
        "Code": "GIW",
        "Spell": "GY|GUIYANG"
    }, {
        "Name": "哈尔滨",
        "EnName": "HAERBIN",
        "Code": "HBB",
        "Spell": "HEB|HAERBIN"
    }, {
        "Name": "合肥",
        "EnName": "HEFEI",
        "Code": "HFH",
        "Spell": "HF|HEFEI"
    }, {
        "Name": "杭州",
        "EnName": "HANGZHOU",
        "Code": "HZH",
        "Spell": "HZ|HANGZHOU"
    }, {
        "Name": "海口",
        "EnName": "HAIKOU",
        "Code": "VUQ",
        "Spell": "HK|HAIKOU"
    }, {
        "Name": "济南",
        "EnName": "JINAN",
        "Code": "JNK",
        "Spell": "JN|JINAN"
    },  {
        "Name": "昆明",
        "EnName": "KUNMING",
        "Code": "KMM",
        "Spell": "KM|KUNMING"
    }, {
        "Name": "拉萨",
        "EnName": "LASA",
        "Code": "LSO",
        "Spell": "LS|LASA"
    }, {
        "Name": "兰州",
        "EnName": "LANZHOU",
        "Code": "LZJ",
        "Spell": "LZ|LANZHOU"
    }, {
        "Name": "南宁",
        "EnName": "NANNING",
        "Code": "NNZ",
        "Spell": "NN|NANNING"
    }, {
        "Name": "南京",
        "EnName": "NANJING",
        "Code": "NJH",
        "Spell": "NJ|NANJING"
    }, {
        "Name": "南昌",
        "EnName": "NANCHANG",
        "Code": "NCG",
        "Spell": "NC|NANCHANG"
    }, {
        "Name": "沈阳",
        "EnName": "SHENYANG",
        "Code": "SYT",
        "Spell": "SY|SHENYANG"
    }, {
        "Name": "太原",
        "EnName": "TAIYUAN",
        "Code": "TYV",
        "Spell": "TY|TAIYUAN"
    }, {
        "Name": "武汉",
        "EnName": "WUHAN",
        "Code": "WHN",
        "Spell": "WH|WUHAN"
    }, {
        "Name": "西宁",
        "EnName": "XINING",
        "Code": "XNO",
        "Spell": "XN|XINING"
    }, {
        "Name": "西安",
        "EnName": "XIAN",
        "Code": "XAY",
        "Spell": "XA|XIAN"
    }, {
        "Name": "银川",
        "EnName": "YINCHUAN",
        "Code": "YIJ",
        "Spell": "YC|YINCHUAN"
    }, {
        "Name": "郑州",
        "EnName": "ZHENGZHOU",
        "Code": "ZZF",
        "Spell": "ZZ|ZHENGZHOU"
    }, {
        "Name": "深圳",
        "EnName": "SHENZHEN",
        "Code": "SZQ",
        "Spell": "SZ|SHENZHEN"
    }, {
        "Name": "厦门",
        "EnName": "XIAMEN",
        "Code": "XMS",
        "Spell": "XM|XIAMEN"
    }

]

export default TrainHotData;